// Generated by stratus_hls 19.12-s100  (91710.131054)
// Thu May  6 05:53:36 2021
// from ../Gaussian_Blur.cpp
#ifndef CYNTH_PART_Gaussian_Blur_Gaussian_Blur_rtl_h
#define CYNTH_PART_Gaussian_Blur_Gaussian_Blur_rtl_h

#include "systemc.h"
/* Include declarations of instantiated parts. */
#include "Gaussian_Blur_ROM_9X9_filter.h"


/* Declaration of the synthesized module. */
struct Gaussian_Blur : public sc_module {
  sc_in<bool > i_clk;
  sc_in<bool > i_rst;
  sc_out<bool > i_rgb_busy;
  sc_in<bool > i_rgb_vld;
  sc_in<sc_int<25> > i_rgb_data;
  sc_in<bool > o_result_busy;
  sc_out<bool > o_result_vld;
  sc_out<sc_int<32> > o_result_data;
  Gaussian_Blur( sc_module_name name );
  SC_HAS_PROCESS(Gaussian_Blur);
  sc_signal<bool > o_result_m_req_m_prev_trig_req;
  sc_signal<sc_uint<1> > Gaussian_Blur_Xor_1Ux1U_1U_1_1_out1;
  sc_signal<bool > o_result_m_unacked_req;
  sc_signal<sc_uint<1> > Gaussian_Blur_Or_1Ux1U_1U_4_2_out1;
  sc_signal<sc_uint<1> > Gaussian_Blur_N_Muxb_1_2_1_4_4_out1;
  sc_signal<bool > i_rgb_m_unvalidated_req;
  sc_signal<sc_uint<1> > 
  Gaussian_Blur_gen_busy_r_4_28_gen_busy_i_rgb_m_data_is_invalid_next;
  sc_signal<sc_uint<1> > Gaussian_Blur_gen_busy_r_4_28_gdiv;
  sc_signal<sc_uint<1> > Gaussian_Blur_gen_busy_r_4_28_gnew_req;
  sc_signal<sc_uint<9> > Gaussian_Blur_N_Mux_9_2_2_4_31_out1;
  sc_signal<sc_int<9> > stall_fifo_1_stall_fifo_1_0;
  sc_signal<sc_uint<1> > active_0;
  sc_signal<sc_uint<1> > Gaussian_Blur_gen_fifo_addr_alt0_4_29_amtmp004;
  sc_signal<sc_uint<1> > Gaussian_Blur_gen_fifo_addr_alt0_4_29_amtmp003;
  sc_signal<sc_uint<1> > Gaussian_Blur_gen_fifo_addr_alt0_4_29_out1;
  sc_signal<sc_uint<1> > fifo_dsel;
  sc_signal<sc_uint<3> > global_state_next;
  sc_signal<sc_uint<1> > r_busy;
  sc_signal<sc_uint<1> > gs_ctrl9;
  sc_signal<sc_uint<1> > Gaussian_Blur_N_Mux_11_2_0_4_25_ctrl1;
  sc_signal<sc_int<11> > Gaussian_Blur_Minus_11U_11S_4_23_out1;
  sc_signal<sc_uint<11> > Gaussian_Blur_Abs_11S_11U_4_20_out1;
  sc_signal<sc_int<9> > Gaussian_Blur_Add_9Sx9S_10S_4_13_in2;
  sc_signal<sc_uint<1> > gs_ctrl8;
  sc_signal<sc_int<9> > Gaussian_Blur_Add_10Sx9S_11S_4_12_in1;
  sc_signal<sc_uint<1> > gs_ctrl7;
  sc_signal<sc_int<10> > Gaussian_Blur_Add_10Sx9S_11S_4_12_in2;
  sc_signal<sc_uint<1> > gs_ctrl6;
  sc_signal<sc_int<9> > Gaussian_Blur_Mul_9Sx8U_9S_4_11_out1;
  sc_signal<sc_uint<8> > Gaussian_Blur_Mul_9Sx8U_9S_4_11_in1;
  sc_signal<sc_int<9> > Gaussian_Blur_Mul_9Sx8U_9S_4_10_out1;
  sc_signal<sc_uint<8> > Gaussian_Blur_Mul_9Sx8U_9S_4_10_in1;
  sc_signal<sc_int<9> > Gaussian_Blur_Mul_9Sx8U_9S_4_10_in2;
  sc_signal<sc_uint<2> > Gaussian_Blur_Add_2Ux1U_2U_4_9_in2;
  sc_signal<sc_uint<4> > Gaussian_Blur_Add_4Ux2U_4U_4_8_out1;
  sc_signal<sc_uint<2> > Gaussian_Blur_Add_4Ux2U_4U_4_8_in1;
  sc_signal<sc_uint<4> > Gaussian_Blur_Mul_2Ux2U_4U_4_7_out1;
  sc_signal<sc_uint<2> > Gaussian_Blur_Mul_2Ux2U_4U_4_7_in2;
  sc_signal<sc_uint<2> > Gaussian_Blur_Add_2Ux1U_2U_4_6_in2;
  sc_signal<sc_uint<1> > gs_ctrl0;
  sc_signal<sc_uint<11> > Gaussian_Blur_Div_11Ux2U_11U_4_21_out1;
  sc_signal<sc_uint<11> > s_reg_27;
  sc_signal<sc_uint<9> > Gaussian_Blur_N_Mux_9_2_2_1_30_out1;
  sc_signal<sc_uint<10> > s_reg_26;
  sc_signal<sc_uint<2> > Gaussian_Blur_Add_2Ux1U_2U_4_9_out1;
  sc_signal<sc_uint<2> > s_reg_25;
  sc_signal<sc_uint<9> > s_reg_24;
  sc_signal<sc_int<10> > Gaussian_Blur_Add_9Sx9S_10S_4_13_out1;
  sc_signal<sc_uint<9> > s_reg_23;
  sc_signal<sc_int<11> > Gaussian_Blur_Add_10Sx9S_11S_4_12_out1;
  sc_signal<sc_uint<9> > s_reg_22;
  sc_signal<sc_uint<2> > Gaussian_Blur_Add_2Ux1U_2U_4_6_out1;
  sc_signal<sc_uint<2> > s_reg_21;
  sc_signal<sc_uint<2> > s_reg_20;
  sc_signal<sc_uint<3> > Gaussian_Blur_gen_busy_r_4_28_out1;
  sc_signal<sc_uint<1> > Gaussian_Blur_And_1Ux1U_1U_4_26_out1;
  sc_signal<sc_uint<1> > Gaussian_Blur_Not_1U_1U_1_3_out1;
  sc_signal<bool > o_result_m_req_m_trig_req;
  sc_signal<sc_uint<1> > Gaussian_Blur_LessThan_2Ux2U_1U_4_16_out1;
  sc_signal<sc_uint<1> > Gaussian_Blur_LessThan_2Ux2U_1U_4_17_out1;
  sc_signal<bool > i_rgb_m_busy_req_0;
  sc_signal<sc_uint<11> > Gaussian_Blur_N_Mux_11_2_0_4_25_out1;
  sc_signal<sc_int<24> > o_result_data_slice;
  sc_signal<sc_uint<3> > global_state;
  sc_signal<sc_uint<1> > stall0;
  sc_signal<sc_uint<4> > filter_in1;
  sc_signal<sc_uint<9> > filter_out1;
  Gaussian_Blur_ROM_9X9_filter *filter;
  void drive_o_result_data_slice();
  void drive_i_rgb_m_busy_req_0();
  void drive_o_result_m_req_m_trig_req();
  void drive_stall0();
  void drive_s_reg_20();
  void drive_s_reg_21();
  void drive_s_reg_22();
  void drive_s_reg_23();
  void drive_s_reg_24();
  void drive_s_reg_25();
  void drive_s_reg_26();
  void drive_s_reg_27();
  void drive_Gaussian_Blur_Add_2Ux1U_2U_4_6_in2();
  void Gaussian_Blur_Add_2Ux1U_2U_4_6();
  void drive_Gaussian_Blur_Mul_2Ux2U_4U_4_7_in2();
  void Gaussian_Blur_Mul_2Ux2U_4U_4_7();
  void drive_Gaussian_Blur_Add_4Ux2U_4U_4_8_in1();
  void Gaussian_Blur_Add_4Ux2U_4U_4_8();
  void drive_Gaussian_Blur_Add_2Ux1U_2U_4_9_in2();
  void Gaussian_Blur_Add_2Ux1U_2U_4_9();
  void drive_filter_in1();
  void drive_Gaussian_Blur_Mul_9Sx8U_9S_4_10_in2();
  void drive_Gaussian_Blur_Mul_9Sx8U_9S_4_10_in1();
  void Gaussian_Blur_Mul_9Sx8U_9S_4_10();
  void drive_Gaussian_Blur_Mul_9Sx8U_9S_4_11_in1();
  void Gaussian_Blur_Mul_9Sx8U_9S_4_11();
  void drive_Gaussian_Blur_Add_10Sx9S_11S_4_12_in2();
  void drive_Gaussian_Blur_Add_10Sx9S_11S_4_12_in1();
  void Gaussian_Blur_Add_10Sx9S_11S_4_12();
  void drive_Gaussian_Blur_Add_9Sx9S_10S_4_13_in2();
  void Gaussian_Blur_Add_9Sx9S_10S_4_13();
  void Gaussian_Blur_LessThan_2Ux2U_1U_4_16();
  void Gaussian_Blur_LessThan_2Ux2U_1U_4_17();
  void Gaussian_Blur_Abs_11S_11U_4_20();
  void Gaussian_Blur_Div_11Ux2U_11U_4_21();
  void Gaussian_Blur_Minus_11U_11S_4_23();
  void drive_Gaussian_Blur_N_Mux_11_2_0_4_25_ctrl1();
  void Gaussian_Blur_N_Mux_11_2_0_4_25();
  void drive_r_busy();
  void drive_global_state();
  void drive_global_state_next();
  void drive_gs_ctrl0();
  void drive_gs_ctrl6();
  void drive_gs_ctrl7();
  void drive_gs_ctrl8();
  void drive_gs_ctrl9();
  void drive_fifo_dsel();
  void Gaussian_Blur_gen_fifo_addr_alt0_4_29_p4();
  void Gaussian_Blur_gen_fifo_addr_alt0_4_29_p3();
  void Gaussian_Blur_gen_fifo_addr_alt0_4_29_p2();
  void Gaussian_Blur_N_Mux_9_2_2_1_30();
  void drive_stall_fifo_1_stall_fifo_1_0();
  void Gaussian_Blur_N_Mux_9_2_2_4_31();
  void drive_active_0();
  void drive_i_rgb_busy();
  void Gaussian_Blur_gen_busy_r_4_28_p8();
  void Gaussian_Blur_gen_busy_r_4_28_p7();
  void Gaussian_Blur_gen_busy_r_4_28_p6();
  void Gaussian_Blur_gen_busy_r_4_28_p5();
  void drive_i_rgb_m_unvalidated_req();
  void Gaussian_Blur_N_Muxb_1_2_1_4_4();
  void drive_o_result_vld();
  void Gaussian_Blur_Or_1Ux1U_1U_4_2();
  void drive_o_result_m_unacked_req();
  void Gaussian_Blur_And_1Ux1U_1U_4_26();
  void Gaussian_Blur_Xor_1Ux1U_1U_1_1();
  void drive_o_result_m_req_m_prev_trig_req();
  void Gaussian_Blur_Not_1U_1U_1_3();
  void drive_o_result_data();
};

#endif
