`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  6 2021 05:27:09 CST (May  5 2021 21:27:09 UTC)

module Gaussian_Blur_Add_4Sx2U_5S_4(in2, in1, out1);
  input [3:0] in2;
  input [1:0] in1;
  output [4:0] out1;
  wire [3:0] in2;
  wire [1:0] in1;
  wire [4:0] out1;
  wire add_23_2_n_0, add_23_2_n_3, add_23_2_n_4, add_23_2_n_7;
  INVX1 add_23_2_g85(.A (add_23_2_n_7), .Y (out1[3]));
  ADDHX1 add_23_2_g86(.A (in2[3]), .B (add_23_2_n_4), .CO (out1[4]), .S
       (add_23_2_n_7));
  XOR2XL add_23_2_g87(.A (in2[2]), .B (add_23_2_n_3), .Y (out1[2]));
  NAND2X1 add_23_2_g88(.A (in2[2]), .B (add_23_2_n_3), .Y
       (add_23_2_n_4));
  ADDFX1 add_23_2_g89(.A (add_23_2_n_0), .B (in1[1]), .CI (in2[1]), .CO
       (add_23_2_n_3), .S (out1[1]));
  ADDHX1 add_23_2_g90(.A (in2[0]), .B (in1[0]), .CO (add_23_2_n_0), .S
       (out1[0]));
endmodule


