`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  6 2021 05:28:40 CST (May  5 2021 21:28:40 UTC)

module Gaussian_Blur_Abs_32S_32U_1(in1, out1);
  input [31:0] in1;
  output [31:0] out1;
  wire [31:0] in1;
  wire [31:0] out1;
  wire minus_20_14_n_4, minus_20_14_n_5, minus_20_14_n_6,
       minus_20_14_n_7, minus_20_14_n_8, minus_20_14_n_9,
       minus_20_14_n_10, minus_20_14_n_11;
  wire minus_20_14_n_12, minus_20_14_n_13, minus_20_14_n_14,
       minus_20_14_n_15, minus_20_14_n_16, minus_20_14_n_17,
       minus_20_14_n_18, minus_20_14_n_19;
  wire minus_20_14_n_20, minus_20_14_n_21, minus_20_14_n_22,
       minus_20_14_n_23, minus_20_14_n_24, minus_20_14_n_25,
       minus_20_14_n_26, minus_20_14_n_27;
  wire minus_20_14_n_28, minus_20_14_n_29, minus_20_14_n_30,
       minus_20_14_n_31, minus_20_14_n_32, minus_20_14_n_33,
       minus_20_14_n_34, minus_20_14_n_35;
  wire minus_20_14_n_36, minus_20_14_n_37, minus_20_14_n_38,
       minus_20_14_n_39, minus_20_14_n_40, minus_20_14_n_41,
       minus_20_14_n_42, minus_20_14_n_43;
  wire minus_20_14_n_44, minus_20_14_n_45, minus_20_14_n_46,
       minus_20_14_n_47, minus_20_14_n_48, minus_20_14_n_49,
       minus_20_14_n_50, minus_20_14_n_51;
  wire minus_20_14_n_52, minus_20_14_n_54, minus_20_14_n_55,
       minus_20_14_n_56, minus_20_14_n_57, minus_20_14_n_58,
       minus_20_14_n_59, minus_20_14_n_60;
  wire minus_20_14_n_61, minus_20_14_n_62, minus_20_14_n_63,
       minus_20_14_n_64, minus_20_14_n_65, minus_20_14_n_66,
       minus_20_14_n_67, minus_20_14_n_68;
  wire minus_20_14_n_69, minus_20_14_n_71, minus_20_14_n_72,
       minus_20_14_n_73, minus_20_14_n_74, minus_20_14_n_75,
       minus_20_14_n_76, minus_20_14_n_77;
  wire minus_20_14_n_78, minus_20_14_n_79, minus_20_14_n_80,
       minus_20_14_n_81, minus_20_14_n_82, minus_20_14_n_83,
       minus_20_14_n_84, minus_20_14_n_85;
  wire minus_20_14_n_87, minus_20_14_n_88, minus_20_14_n_89,
       minus_20_14_n_90, minus_20_14_n_91, minus_20_14_n_92,
       minus_20_14_n_94, minus_20_14_n_95;
  wire minus_20_14_n_96, minus_20_14_n_97, minus_20_14_n_98,
       minus_20_14_n_99, minus_20_14_n_100, minus_20_14_n_101,
       minus_20_14_n_102, minus_20_14_n_105;
  wire minus_20_14_n_106, minus_20_14_n_107, minus_20_14_n_108,
       minus_20_14_n_109, minus_20_14_n_110, minus_20_14_n_111,
       minus_20_14_n_112, minus_20_14_n_169;
  wire minus_20_14_n_172, minus_20_14_n_180, minus_20_14_n_181,
       minus_20_14_n_182, minus_20_14_n_184, minus_20_14_n_187,
       minus_20_14_n_188, minus_20_14_n_195;
  wire minus_20_14_n_198, minus_20_14_n_199, minus_20_14_n_200,
       minus_20_14_n_201, minus_20_14_n_202, n_0, n_1, n_2;
  wire n_3, n_4, n_5, n_6, n_7, n_8, n_9, n_10;
  wire n_11, n_12, n_13, n_14, n_15, n_16, n_17, n_18;
  wire n_19, n_20, n_21, n_22, n_23, n_24, n_25, n_26;
  wire n_27, n_28, n_29, n_30, n_31, n_32, n_33, n_34;
  wire n_35, n_36, n_37, n_38, n_39, n_40, n_41, n_42;
  wire n_43, n_44, n_45, n_46, n_47, n_48, n_49, n_50;
  wire n_51, n_52, n_53, n_54, n_55, n_56, n_57, n_58;
  wire n_59, n_60, n_61;
  assign out1[0] = in1[0];
  OAI2BB1XL g310(.A0N (in1[31]), .A1N (n_47), .B0 (n_24), .Y
       (out1[17]));
  OAI2BB1XL g311(.A0N (in1[31]), .A1N (n_59), .B0 (n_12), .Y
       (out1[29]));
  OAI2BB1XL g312(.A0N (in1[31]), .A1N (n_57), .B0 (n_1), .Y (out1[27]));
  OAI2BB1XL g313(.A0N (in1[31]), .A1N (n_54), .B0 (n_22), .Y
       (out1[24]));
  OAI2BB1XL g314(.A0N (in1[31]), .A1N (n_48), .B0 (n_28), .Y
       (out1[18]));
  OAI2BB1XL g315(.A0N (in1[31]), .A1N (n_35), .B0 (n_29), .Y (out1[5]));
  OAI2BB1X1 g316(.A0N (in1[31]), .A1N (n_34), .B0 (n_27), .Y (out1[4]));
  OAI2BB1XL g317(.A0N (in1[31]), .A1N (n_60), .B0 (n_4), .Y (out1[30]));
  OAI2BB1X1 g318(.A0N (in1[31]), .A1N (n_33), .B0 (n_25), .Y (out1[3]));
  OAI2BB1XL g319(.A0N (in1[31]), .A1N (n_53), .B0 (n_18), .Y
       (out1[23]));
  OAI2BB1X1 g320(.A0N (in1[31]), .A1N (n_46), .B0 (n_21), .Y
       (out1[16]));
  OAI2BB1X1 g321(.A0N (in1[2]), .A1N (n_0), .B0 (n_30), .Y (out1[2]));
  OAI2BB1X1 g322(.A0N (in1[31]), .A1N (n_31), .B0 (n_20), .Y (out1[1]));
  OAI2BB1X1 g323(.A0N (in1[31]), .A1N (n_45), .B0 (n_19), .Y
       (out1[15]));
  OAI2BB1XL g324(.A0N (in1[31]), .A1N (n_52), .B0 (n_14), .Y
       (out1[22]));
  OAI2BB1XL g325(.A0N (in1[31]), .A1N (n_50), .B0 (n_6), .Y (out1[20]));
  OAI2BB1X1 g326(.A0N (in1[31]), .A1N (n_43), .B0 (n_15), .Y
       (out1[13]));
  OAI2BB1X1 g327(.A0N (in1[31]), .A1N (n_42), .B0 (n_13), .Y
       (out1[12]));
  OAI2BB1XL g328(.A0N (in1[31]), .A1N (n_58), .B0 (n_26), .Y
       (out1[28]));
  OAI2BB1XL g329(.A0N (in1[31]), .A1N (n_56), .B0 (n_8), .Y (out1[26]));
  OAI2BB1XL g330(.A0N (in1[31]), .A1N (n_51), .B0 (n_10), .Y
       (out1[21]));
  OAI2BB1X1 g331(.A0N (in1[31]), .A1N (n_41), .B0 (n_11), .Y
       (out1[11]));
  OAI2BB1X1 g332(.A0N (in1[31]), .A1N (n_44), .B0 (n_17), .Y
       (out1[14]));
  OAI2BB1X1 g333(.A0N (in1[31]), .A1N (n_40), .B0 (n_9), .Y (out1[10]));
  OAI2BB1X1 g334(.A0N (in1[31]), .A1N (n_39), .B0 (n_7), .Y (out1[9]));
  OAI2BB1XL g335(.A0N (in1[31]), .A1N (n_55), .B0 (n_23), .Y
       (out1[25]));
  OAI2BB1XL g336(.A0N (in1[31]), .A1N (n_49), .B0 (n_2), .Y (out1[19]));
  OAI2BB1XL g337(.A0N (in1[31]), .A1N (n_38), .B0 (n_5), .Y (out1[8]));
  OAI2BB1XL g338(.A0N (in1[31]), .A1N (n_37), .B0 (n_3), .Y (out1[7]));
  OAI2BB1XL g339(.A0N (in1[31]), .A1N (n_36), .B0 (n_16), .Y (out1[6]));
  NAND2X1 g340(.A (in1[31]), .B (n_32), .Y (n_30));
  NAND2X1 g341(.A (in1[5]), .B (n_0), .Y (n_29));
  NAND2XL g342(.A (in1[18]), .B (n_0), .Y (n_28));
  NAND2X1 g343(.A (in1[4]), .B (n_0), .Y (n_27));
  NAND2XL g344(.A (in1[28]), .B (n_0), .Y (n_26));
  NAND2X1 g345(.A (in1[3]), .B (n_0), .Y (n_25));
  NAND2XL g346(.A (in1[17]), .B (n_0), .Y (n_24));
  NAND2XL g347(.A (in1[25]), .B (n_0), .Y (n_23));
  NAND2XL g348(.A (in1[24]), .B (n_0), .Y (n_22));
  NAND2X1 g349(.A (in1[16]), .B (n_0), .Y (n_21));
  NAND2X1 g350(.A (in1[1]), .B (n_0), .Y (n_20));
  NOR2BX1 g351(.AN (n_61), .B (n_0), .Y (out1[31]));
  NAND2X1 g352(.A (in1[15]), .B (n_0), .Y (n_19));
  NAND2XL g353(.A (in1[23]), .B (n_0), .Y (n_18));
  NAND2X1 g354(.A (in1[14]), .B (n_0), .Y (n_17));
  NAND2X1 g355(.A (in1[6]), .B (n_0), .Y (n_16));
  NAND2X1 g356(.A (in1[13]), .B (n_0), .Y (n_15));
  NAND2XL g357(.A (in1[22]), .B (n_0), .Y (n_14));
  NAND2X1 g358(.A (in1[12]), .B (n_0), .Y (n_13));
  NAND2XL g359(.A (in1[29]), .B (n_0), .Y (n_12));
  NAND2X1 g360(.A (in1[11]), .B (n_0), .Y (n_11));
  NAND2XL g361(.A (in1[21]), .B (n_0), .Y (n_10));
  NAND2X1 g362(.A (in1[10]), .B (n_0), .Y (n_9));
  NAND2XL g363(.A (in1[26]), .B (n_0), .Y (n_8));
  NAND2X1 g364(.A (in1[9]), .B (n_0), .Y (n_7));
  NAND2XL g365(.A (in1[20]), .B (n_0), .Y (n_6));
  NAND2X1 g366(.A (in1[8]), .B (n_0), .Y (n_5));
  NAND2XL g367(.A (in1[30]), .B (n_0), .Y (n_4));
  NAND2X1 g368(.A (in1[7]), .B (n_0), .Y (n_3));
  NAND2XL g369(.A (in1[19]), .B (n_0), .Y (n_2));
  NAND2XL g370(.A (in1[27]), .B (n_0), .Y (n_1));
  CLKINVX4 g371(.A (in1[31]), .Y (n_0));
  MXI2XL minus_20_14_g739(.A (in1[17]), .B (minus_20_14_n_19), .S0
       (minus_20_14_n_111), .Y (n_47));
  MXI2XL minus_20_14_g740(.A (minus_20_14_n_32), .B (in1[9]), .S0
       (minus_20_14_n_96), .Y (n_39));
  MXI2XL minus_20_14_g741(.A (in1[24]), .B (minus_20_14_n_14), .S0
       (minus_20_14_n_109), .Y (n_54));
  MXI2XL minus_20_14_g742(.A (in1[27]), .B (minus_20_14_n_27), .S0
       (minus_20_14_n_97), .Y (n_57));
  MXI2XL minus_20_14_g743(.A (in1[23]), .B (minus_20_14_n_29), .S0
       (minus_20_14_n_105), .Y (n_53));
  MXI2XL minus_20_14_g745(.A (in1[19]), .B (minus_20_14_n_20), .S0
       (minus_20_14_n_100), .Y (n_49));
  MXI2XL minus_20_14_g746(.A (in1[25]), .B (minus_20_14_n_30), .S0
       (minus_20_14_n_101), .Y (n_55));
  MXI2XL minus_20_14_g747(.A (in1[29]), .B (minus_20_14_n_18), .S0
       (minus_20_14_n_98), .Y (n_59));
  MXI2XL minus_20_14_g748(.A (in1[18]), .B (minus_20_14_n_13), .S0
       (minus_20_14_n_4), .Y (n_48));
  MXI2XL minus_20_14_g749(.A (in1[21]), .B (minus_20_14_n_31), .S0
       (minus_20_14_n_102), .Y (n_51));
  MXI2XL minus_20_14_g750(.A (in1[26]), .B (minus_20_14_n_11), .S0
       (minus_20_14_n_99), .Y (n_56));
  MXI2XL minus_20_14_g751(.A (in1[22]), .B (minus_20_14_n_25), .S0
       (minus_20_14_n_106), .Y (n_52));
  MXI2XL minus_20_14_g752(.A (in1[20]), .B (minus_20_14_n_24), .S0
       (minus_20_14_n_110), .Y (n_50));
  MXI2XL minus_20_14_g753(.A (minus_20_14_n_34), .B (in1[31]), .S0
       (minus_20_14_n_108), .Y (n_61));
  XOR2XL minus_20_14_g754(.A (in1[30]), .B (minus_20_14_n_112), .Y
       (n_60));
  MXI2XL minus_20_14_g755(.A (in1[28]), .B (minus_20_14_n_15), .S0
       (minus_20_14_n_107), .Y (n_58));
  MXI2XL minus_20_14_g756(.A (minus_20_14_n_33), .B (in1[15]), .S0
       (minus_20_14_n_90), .Y (n_45));
  MXI2XL minus_20_14_g758(.A (minus_20_14_n_17), .B (in1[11]), .S0
       (minus_20_14_n_89), .Y (n_41));
  MXI2XL minus_20_14_g759(.A (minus_20_14_n_23), .B (in1[16]), .S0
       (minus_20_14_n_199), .Y (n_46));
  MXI2XL minus_20_14_g760(.A (minus_20_14_n_12), .B (in1[14]), .S0
       (minus_20_14_n_92), .Y (n_44));
  MXI2XL minus_20_14_g761(.A (minus_20_14_n_28), .B (in1[13]), .S0
       (minus_20_14_n_91), .Y (n_43));
  MXI2XL minus_20_14_g762(.A (minus_20_14_n_22), .B (in1[12]), .S0
       (minus_20_14_n_8), .Y (n_42));
  MXI2XL minus_20_14_g763(.A (minus_20_14_n_9), .B (in1[10]), .S0
       (minus_20_14_n_95), .Y (n_40));
  NAND2X1 minus_20_14_g764(.A (minus_20_14_n_94), .B
       (minus_20_14_n_80), .Y (minus_20_14_n_112));
  NOR2XL minus_20_14_g765(.A (in1[16]), .B (minus_20_14_n_198), .Y
       (minus_20_14_n_111));
  NOR2XL minus_20_14_g766(.A (minus_20_14_n_55), .B
       (minus_20_14_n_198), .Y (minus_20_14_n_110));
  NOR2XL minus_20_14_g767(.A (minus_20_14_n_188), .B
       (minus_20_14_n_202), .Y (minus_20_14_n_109));
  NAND2X1 minus_20_14_g768(.A (minus_20_14_n_77), .B
       (minus_20_14_n_200), .Y (minus_20_14_n_108));
  NOR2XL minus_20_14_g769(.A (minus_20_14_n_84), .B
       (minus_20_14_n_195), .Y (minus_20_14_n_107));
  NOR2XL minus_20_14_g770(.A (minus_20_14_n_73), .B
       (minus_20_14_n_195), .Y (minus_20_14_n_106));
  NOR2XL minus_20_14_g771(.A (minus_20_14_n_67), .B
       (minus_20_14_n_195), .Y (minus_20_14_n_105));
  MXI2XL minus_20_14_g773(.A (in1[6]), .B (minus_20_14_n_21), .S0
       (minus_20_14_n_7), .Y (n_36));
  MXI2XL minus_20_14_g775(.A (in1[8]), .B (minus_20_14_n_26), .S0
       (minus_20_14_n_172), .Y (n_38));
  NOR2XL minus_20_14_g776(.A (minus_20_14_n_72), .B
       (minus_20_14_n_201), .Y (minus_20_14_n_102));
  NOR2XL minus_20_14_g777(.A (minus_20_14_n_81), .B
       (minus_20_14_n_202), .Y (minus_20_14_n_101));
  NOR2XL minus_20_14_g778(.A (minus_20_14_n_64), .B
       (minus_20_14_n_202), .Y (minus_20_14_n_100));
  NOR2XL minus_20_14_g779(.A (minus_20_14_n_83), .B
       (minus_20_14_n_195), .Y (minus_20_14_n_99));
  NOR2XL minus_20_14_g780(.A (minus_20_14_n_78), .B
       (minus_20_14_n_202), .Y (minus_20_14_n_98));
  NOR2XL minus_20_14_g781(.A (minus_20_14_n_76), .B
       (minus_20_14_n_201), .Y (minus_20_14_n_97));
  NAND2X1 minus_20_14_g782(.A (minus_20_14_n_26), .B
       (minus_20_14_n_172), .Y (minus_20_14_n_96));
  NAND2X1 minus_20_14_g783(.A (minus_20_14_n_40), .B
       (minus_20_14_n_172), .Y (minus_20_14_n_95));
  CLKAND2X3 minus_20_14_g786(.A (minus_20_14_n_68), .B
       (minus_20_14_n_87), .Y (minus_20_14_n_94));
  NAND2X1 minus_20_14_g787(.A (minus_20_14_n_6), .B
       (minus_20_14_n_172), .Y (minus_20_14_n_92));
  NAND2X1 minus_20_14_g788(.A (minus_20_14_n_69), .B
       (minus_20_14_n_172), .Y (minus_20_14_n_91));
  NAND2X1 minus_20_14_g789(.A (minus_20_14_n_65), .B
       (minus_20_14_n_172), .Y (minus_20_14_n_90));
  NAND2X1 minus_20_14_g791(.A (minus_20_14_n_60), .B
       (minus_20_14_n_172), .Y (minus_20_14_n_89));
  NOR2X1 minus_20_14_g793(.A (in1[4]), .B (minus_20_14_n_169), .Y
       (minus_20_14_n_88));
  NOR2X6 minus_20_14_g794(.A (minus_20_14_n_79), .B (minus_20_14_n_50),
       .Y (minus_20_14_n_87));
  MXI2XL minus_20_14_g795(.A (in1[2]), .B (minus_20_14_n_10), .S0
       (minus_20_14_n_39), .Y (n_32));
  NOR2X1 minus_20_14_g796(.A (minus_20_14_n_63), .B
       (minus_20_14_n_169), .Y (minus_20_14_n_85));
  NAND2XL minus_20_14_g797(.A (minus_20_14_n_58), .B
       (minus_20_14_n_71), .Y (minus_20_14_n_84));
  NAND2XL minus_20_14_g798(.A (minus_20_14_n_47), .B
       (minus_20_14_n_71), .Y (minus_20_14_n_83));
  NAND2X1 minus_20_14_g799(.A (minus_20_14_n_10), .B
       (minus_20_14_n_39), .Y (minus_20_14_n_82));
  NAND2XL minus_20_14_g800(.A (minus_20_14_n_14), .B
       (minus_20_14_n_71), .Y (minus_20_14_n_81));
  NOR2X1 minus_20_14_g801(.A (minus_20_14_n_74), .B
       (minus_20_14_n_187), .Y (minus_20_14_n_80));
  NAND2X6 minus_20_14_g802(.A (minus_20_14_n_44), .B
       (minus_20_14_n_39), .Y (minus_20_14_n_79));
  NAND2XL minus_20_14_g803(.A (minus_20_14_n_75), .B
       (minus_20_14_n_71), .Y (minus_20_14_n_78));
  NOR2X1 minus_20_14_g804(.A (minus_20_14_n_66), .B
       (minus_20_14_n_188), .Y (minus_20_14_n_77));
  NAND2XL minus_20_14_g805(.A (minus_20_14_n_62), .B
       (minus_20_14_n_71), .Y (minus_20_14_n_76));
  NOR2XL minus_20_14_g806(.A (in1[28]), .B (minus_20_14_n_57), .Y
       (minus_20_14_n_75));
  NAND2X1 minus_20_14_g808(.A (minus_20_14_n_42), .B
       (minus_20_14_n_58), .Y (minus_20_14_n_74));
  NAND2X1 minus_20_14_g809(.A (minus_20_14_n_46), .B
       (minus_20_14_n_54), .Y (minus_20_14_n_73));
  NAND2X1 minus_20_14_g810(.A (minus_20_14_n_24), .B
       (minus_20_14_n_54), .Y (minus_20_14_n_72));
  NOR2X1 minus_20_14_g812(.A (in1[12]), .B (minus_20_14_n_184), .Y
       (minus_20_14_n_69));
  NOR2X2 minus_20_14_g813(.A (minus_20_14_n_52), .B (minus_20_14_n_56),
       .Y (minus_20_14_n_68));
  NAND2X1 minus_20_14_g814(.A (minus_20_14_n_61), .B
       (minus_20_14_n_54), .Y (minus_20_14_n_67));
  NAND2X1 minus_20_14_g815(.A (minus_20_14_n_5), .B (minus_20_14_n_58),
       .Y (minus_20_14_n_66));
  NOR2X1 minus_20_14_g816(.A (minus_20_14_n_59), .B
       (minus_20_14_n_184), .Y (minus_20_14_n_65));
  NOR2X2 minus_20_14_g817(.A (minus_20_14_n_51), .B (minus_20_14_n_55),
       .Y (minus_20_14_n_71));
  NAND2X1 minus_20_14_g818(.A (minus_20_14_n_13), .B
       (minus_20_14_n_41), .Y (minus_20_14_n_64));
  NAND2X1 minus_20_14_g819(.A (minus_20_14_n_21), .B
       (minus_20_14_n_49), .Y (minus_20_14_n_63));
  AND2XL minus_20_14_g820(.A (minus_20_14_n_11), .B (minus_20_14_n_47),
       .Y (minus_20_14_n_62));
  AND2XL minus_20_14_g821(.A (minus_20_14_n_25), .B (minus_20_14_n_46),
       .Y (minus_20_14_n_61));
  AND2XL minus_20_14_g822(.A (minus_20_14_n_9), .B (minus_20_14_n_40),
       .Y (minus_20_14_n_60));
  NAND2X1 minus_20_14_g824(.A (minus_20_14_n_12), .B
       (minus_20_14_n_181), .Y (minus_20_14_n_59));
  INVX1 minus_20_14_g825(.A (minus_20_14_n_57), .Y (minus_20_14_n_58));
  INVX1 minus_20_14_g827(.A (minus_20_14_n_55), .Y (minus_20_14_n_54));
  MXI2XL minus_20_14_g828(.A (minus_20_14_n_16), .B (in1[1]), .S0
       (in1[0]), .Y (n_31));
  NAND2X2 minus_20_14_g829(.A (minus_20_14_n_43), .B
       (minus_20_14_n_48), .Y (minus_20_14_n_52));
  NAND2X1 minus_20_14_g830(.A (minus_20_14_n_36), .B
       (minus_20_14_n_46), .Y (minus_20_14_n_51));
  NAND2X4 minus_20_14_g831(.A (minus_20_14_n_45), .B
       (minus_20_14_n_49), .Y (minus_20_14_n_50));
  NAND2X1 minus_20_14_g832(.A (minus_20_14_n_47), .B
       (minus_20_14_n_35), .Y (minus_20_14_n_57));
  NAND2X4 minus_20_14_g833(.A (minus_20_14_n_37), .B
       (minus_20_14_n_40), .Y (minus_20_14_n_56));
  NAND2X2 minus_20_14_g834(.A (minus_20_14_n_41), .B
       (minus_20_14_n_38), .Y (minus_20_14_n_55));
  NOR2X4 minus_20_14_g837(.A (in1[7]), .B (in1[6]), .Y
       (minus_20_14_n_45));
  NOR2X8 minus_20_14_g838(.A (in1[3]), .B (in1[2]), .Y
       (minus_20_14_n_44));
  NOR2X4 minus_20_14_g839(.A (in1[15]), .B (in1[14]), .Y
       (minus_20_14_n_43));
  NOR2X4 minus_20_14_g840(.A (in1[5]), .B (in1[4]), .Y
       (minus_20_14_n_49));
  NOR2X4 minus_20_14_g841(.A (in1[13]), .B (in1[12]), .Y
       (minus_20_14_n_48));
  NOR2X4 minus_20_14_g842(.A (in1[25]), .B (in1[24]), .Y
       (minus_20_14_n_47));
  NOR2X4 minus_20_14_g843(.A (in1[21]), .B (in1[20]), .Y
       (minus_20_14_n_46));
  NOR2X2 minus_20_14_g846(.A (in1[19]), .B (in1[18]), .Y
       (minus_20_14_n_38));
  NOR2X4 minus_20_14_g847(.A (in1[11]), .B (in1[10]), .Y
       (minus_20_14_n_37));
  NOR2X4 minus_20_14_g848(.A (in1[23]), .B (in1[22]), .Y
       (minus_20_14_n_36));
  NOR2X1 minus_20_14_g849(.A (in1[27]), .B (in1[26]), .Y
       (minus_20_14_n_35));
  NOR2X1 minus_20_14_g850(.A (in1[29]), .B (in1[28]), .Y
       (minus_20_14_n_42));
  NOR2X4 minus_20_14_g851(.A (in1[17]), .B (in1[16]), .Y
       (minus_20_14_n_41));
  NOR2X6 minus_20_14_g852(.A (in1[9]), .B (in1[8]), .Y
       (minus_20_14_n_40));
  NOR2X6 minus_20_14_g853(.A (in1[1]), .B (in1[0]), .Y
       (minus_20_14_n_39));
  INVX1 minus_20_14_g854(.A (in1[31]), .Y (minus_20_14_n_34));
  INVX1 minus_20_14_g855(.A (in1[15]), .Y (minus_20_14_n_33));
  INVX1 minus_20_14_g856(.A (in1[9]), .Y (minus_20_14_n_32));
  INVXL minus_20_14_g857(.A (in1[21]), .Y (minus_20_14_n_31));
  INVXL minus_20_14_g858(.A (in1[25]), .Y (minus_20_14_n_30));
  INVXL minus_20_14_g860(.A (in1[23]), .Y (minus_20_14_n_29));
  INVX1 minus_20_14_g861(.A (in1[13]), .Y (minus_20_14_n_28));
  INVXL minus_20_14_g862(.A (in1[27]), .Y (minus_20_14_n_27));
  INVX1 minus_20_14_g863(.A (in1[8]), .Y (minus_20_14_n_26));
  INVX1 minus_20_14_g865(.A (in1[22]), .Y (minus_20_14_n_25));
  INVX1 minus_20_14_g866(.A (in1[20]), .Y (minus_20_14_n_24));
  INVX1 minus_20_14_g867(.A (in1[16]), .Y (minus_20_14_n_23));
  INVX1 minus_20_14_g868(.A (in1[12]), .Y (minus_20_14_n_22));
  INVX1 minus_20_14_g869(.A (in1[6]), .Y (minus_20_14_n_21));
  INVXL minus_20_14_g870(.A (in1[19]), .Y (minus_20_14_n_20));
  INVXL minus_20_14_g872(.A (in1[17]), .Y (minus_20_14_n_19));
  INVXL minus_20_14_g873(.A (in1[29]), .Y (minus_20_14_n_18));
  INVX1 minus_20_14_g875(.A (in1[11]), .Y (minus_20_14_n_17));
  INVX1 minus_20_14_g876(.A (in1[1]), .Y (minus_20_14_n_16));
  INVXL minus_20_14_g877(.A (in1[28]), .Y (minus_20_14_n_15));
  INVX1 minus_20_14_g878(.A (in1[24]), .Y (minus_20_14_n_14));
  INVX1 minus_20_14_g879(.A (in1[18]), .Y (minus_20_14_n_13));
  INVX1 minus_20_14_g880(.A (in1[14]), .Y (minus_20_14_n_12));
  INVX1 minus_20_14_g881(.A (in1[26]), .Y (minus_20_14_n_11));
  INVX1 minus_20_14_g882(.A (in1[2]), .Y (minus_20_14_n_10));
  INVX1 minus_20_14_g883(.A (in1[10]), .Y (minus_20_14_n_9));
  NAND2BX1 minus_20_14_g2(.AN (minus_20_14_n_184), .B
       (minus_20_14_n_172), .Y (minus_20_14_n_8));
  NOR2BX1 minus_20_14_g884(.AN (minus_20_14_n_49), .B
       (minus_20_14_n_169), .Y (minus_20_14_n_7));
  NOR2BX1 minus_20_14_g885(.AN (minus_20_14_n_180), .B
       (minus_20_14_n_184), .Y (minus_20_14_n_6));
  NOR2BX1 minus_20_14_g886(.AN (minus_20_14_n_42), .B (in1[30]), .Y
       (minus_20_14_n_5));
  NOR2BX1 minus_20_14_g887(.AN (minus_20_14_n_41), .B
       (minus_20_14_n_201), .Y (minus_20_14_n_4));
  XNOR2XL minus_20_14_g888(.A (in1[7]), .B (minus_20_14_n_85), .Y
       (n_37));
  XOR2XL minus_20_14_g889(.A (in1[4]), .B (minus_20_14_n_169), .Y
       (n_34));
  XOR2XL minus_20_14_g890(.A (in1[3]), .B (minus_20_14_n_82), .Y
       (n_33));
  XNOR2XL minus_20_14_g891(.A (in1[5]), .B (minus_20_14_n_88), .Y
       (n_35));
  BUFX3 minus_20_14_fopt(.A (minus_20_14_n_79), .Y (minus_20_14_n_169));
  BUFX3 minus_20_14_fopt892(.A (minus_20_14_n_87), .Y
       (minus_20_14_n_172));
  INVXL minus_20_14_fopt895(.A (minus_20_14_n_182), .Y
       (minus_20_14_n_180));
  INVXL minus_20_14_fopt896(.A (minus_20_14_n_182), .Y
       (minus_20_14_n_181));
  INVXL minus_20_14_fopt897(.A (minus_20_14_n_48), .Y
       (minus_20_14_n_182));
  BUFX3 minus_20_14_fopt898(.A (minus_20_14_n_56), .Y
       (minus_20_14_n_184));
  CLKINVX1 minus_20_14_fopt899(.A (minus_20_14_n_71), .Y
       (minus_20_14_n_187));
  CLKINVX1 minus_20_14_fopt900(.A (minus_20_14_n_71), .Y
       (minus_20_14_n_188));
  CLKINVX1 minus_20_14_fopt903(.A (minus_20_14_n_94), .Y
       (minus_20_14_n_195));
  INVXL minus_20_14_fopt904(.A (minus_20_14_n_200), .Y
       (minus_20_14_n_199));
  CLKINVX1 minus_20_14_fopt905(.A (minus_20_14_n_198), .Y
       (minus_20_14_n_200));
  CLKINVX1 minus_20_14_fopt906(.A (minus_20_14_n_94), .Y
       (minus_20_14_n_198));
  CLKINVX1 minus_20_14_fopt907(.A (minus_20_14_n_94), .Y
       (minus_20_14_n_201));
  CLKINVX1 minus_20_14_fopt908(.A (minus_20_14_n_94), .Y
       (minus_20_14_n_202));
endmodule


