`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  6 2021 05:33:30 CST (May  5 2021 21:33:30 UTC)

module Gaussian_Blur_Add_10U_1_1(in1, out1);
  input [9:0] in1;
  output [9:0] out1;
  wire [9:0] in1;
  wire [9:0] out1;
  wire add_21_2_n_3, add_21_2_n_4, add_21_2_n_5, add_21_2_n_6,
       add_21_2_n_7, add_21_2_n_8, add_21_2_n_9, add_21_2_n_10;
  wire add_21_2_n_11, add_21_2_n_12, add_21_2_n_13, add_21_2_n_15,
       add_21_2_n_16, add_21_2_n_17, add_21_2_n_18, add_21_2_n_20;
  wire add_21_2_n_21, add_21_2_n_22, add_21_2_n_23;
  INVX1 g7(.A (in1[0]), .Y (out1[0]));
  MXI2X1 add_21_2_g170(.A (add_21_2_n_8), .B (in1[9]), .S0
       (add_21_2_n_23), .Y (out1[9]));
  MXI2XL add_21_2_g172(.A (add_21_2_n_7), .B (in1[3]), .S0
       (add_21_2_n_18), .Y (out1[3]));
  NAND2BX1 add_21_2_g173(.AN (add_21_2_n_3), .B (add_21_2_n_23), .Y
       (out1[8]));
  MXI2XL add_21_2_g175(.A (add_21_2_n_6), .B (in1[6]), .S0
       (add_21_2_n_4), .Y (out1[6]));
  NAND2BX2 add_21_2_g176(.AN (in1[8]), .B (add_21_2_n_21), .Y
       (add_21_2_n_23));
  NAND2X1 add_21_2_g179(.A (in1[4]), .B (add_21_2_n_17), .Y
       (add_21_2_n_22));
  NAND2X2 add_21_2_g181(.A (add_21_2_n_17), .B (add_21_2_n_15), .Y
       (add_21_2_n_21));
  NAND2X1 add_21_2_g182(.A (add_21_2_n_16), .B (add_21_2_n_17), .Y
       (add_21_2_n_20));
  MXI2XL add_21_2_g183(.A (in1[2]), .B (add_21_2_n_5), .S0
       (add_21_2_n_10), .Y (out1[2]));
  NOR2X1 add_21_2_g184(.A (add_21_2_n_5), .B (add_21_2_n_10), .Y
       (add_21_2_n_18));
  NOR2X6 add_21_2_g186(.A (add_21_2_n_11), .B (add_21_2_n_10), .Y
       (add_21_2_n_17));
  NOR2X1 add_21_2_g187(.A (add_21_2_n_6), .B (add_21_2_n_12), .Y
       (add_21_2_n_16));
  NOR2X2 add_21_2_g188(.A (add_21_2_n_13), .B (add_21_2_n_12), .Y
       (add_21_2_n_15));
  MXI2XL add_21_2_g189(.A (add_21_2_n_9), .B (in1[1]), .S0 (in1[0]), .Y
       (out1[1]));
  NAND2X2 add_21_2_g190(.A (in1[7]), .B (in1[6]), .Y (add_21_2_n_13));
  NAND2X6 add_21_2_g191(.A (in1[5]), .B (in1[4]), .Y (add_21_2_n_12));
  NAND2X8 add_21_2_g192(.A (in1[3]), .B (in1[2]), .Y (add_21_2_n_11));
  NAND2X6 add_21_2_g193(.A (in1[1]), .B (in1[0]), .Y (add_21_2_n_10));
  INVX1 add_21_2_g194(.A (in1[1]), .Y (add_21_2_n_9));
  INVXL add_21_2_g195(.A (in1[9]), .Y (add_21_2_n_8));
  INVXL add_21_2_g196(.A (in1[3]), .Y (add_21_2_n_7));
  INVX1 add_21_2_g198(.A (in1[6]), .Y (add_21_2_n_6));
  INVX1 add_21_2_g202(.A (in1[2]), .Y (add_21_2_n_5));
  NOR2BX1 add_21_2_g2(.AN (add_21_2_n_17), .B (add_21_2_n_12), .Y
       (add_21_2_n_4));
  NOR2BX1 add_21_2_g203(.AN (in1[8]), .B (add_21_2_n_21), .Y
       (add_21_2_n_3));
  XOR2XL add_21_2_g204(.A (in1[4]), .B (add_21_2_n_17), .Y (out1[4]));
  XNOR2XL add_21_2_g205(.A (in1[5]), .B (add_21_2_n_22), .Y (out1[5]));
  XNOR2XL add_21_2_g206(.A (in1[7]), .B (add_21_2_n_20), .Y (out1[7]));
endmodule


