`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  6 2021 05:33:23 CST (May  5 2021 21:33:23 UTC)

module Gaussian_Blur_Nen1s32_4(in1, out1);
  input [31:0] in1;
  output out1;
  wire [31:0] in1;
  wire out1;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9;
  OR4X1 g75(.A (n_2), .B (n_1), .C (n_5), .D (n_9), .Y (out1));
  NAND4XL g76(.A (n_8), .B (n_0), .C (in1[29]), .D (in1[28]), .Y (n_9));
  NOR4X1 g77(.A (n_7), .B (n_3), .C (n_6), .D (n_4), .Y (n_8));
  NAND4XL g78(.A (in1[15]), .B (in1[14]), .C (in1[13]), .D (in1[12]),
       .Y (n_7));
  NAND4XL g81(.A (in1[7]), .B (in1[6]), .C (in1[5]), .D (in1[4]), .Y
       (n_6));
  NAND4XL g79(.A (in1[19]), .B (in1[18]), .C (in1[17]), .D (in1[16]),
       .Y (n_5));
  NAND4XL g84(.A (in1[3]), .B (in1[2]), .C (in1[1]), .D (in1[0]), .Y
       (n_4));
  NAND4XL g83(.A (in1[11]), .B (in1[10]), .C (in1[9]), .D (in1[8]), .Y
       (n_3));
  NAND4XL g82(.A (in1[27]), .B (in1[26]), .C (in1[25]), .D (in1[24]),
       .Y (n_2));
  NAND4XL g80(.A (in1[23]), .B (in1[22]), .C (in1[21]), .D (in1[20]),
       .Y (n_1));
  AND2XL g85(.A (in1[31]), .B (in1[30]), .Y (n_0));
endmodule


