`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  6 2021 05:27:30 CST (May  5 2021 21:27:30 UTC)

module Gaussian_Blur_Mul_9Ux2U_10U_4(in2, in1, out1);
  input [8:0] in2;
  input [1:0] in1;
  output [9:0] out1;
  wire [8:0] in2;
  wire [1:0] in1;
  wire [9:0] out1;
  wire mul_22_8_n_0, mul_22_8_n_1, mul_22_8_n_2, mul_22_8_n_3,
       mul_22_8_n_4, mul_22_8_n_5, mul_22_8_n_6, mul_22_8_n_7;
  wire mul_22_8_n_8, mul_22_8_n_9, mul_22_8_n_10, mul_22_8_n_11,
       mul_22_8_n_13, mul_22_8_n_14, mul_22_8_n_15, mul_22_8_n_16;
  wire mul_22_8_n_17, mul_22_8_n_18, mul_22_8_n_19, mul_22_8_n_20,
       mul_22_8_n_21, mul_22_8_n_22, mul_22_8_n_23, mul_22_8_n_24;
  wire mul_22_8_n_25, mul_22_8_n_26, mul_22_8_n_28, mul_22_8_n_29,
       mul_22_8_n_30, mul_22_8_n_31, mul_22_8_n_32, mul_22_8_n_33;
  wire mul_22_8_n_34, mul_22_8_n_35, mul_22_8_n_36, mul_22_8_n_39,
       mul_22_8_n_40, mul_22_8_n_42, mul_22_8_n_43, mul_22_8_n_44;
  wire mul_22_8_n_46, mul_22_8_n_48, mul_22_8_n_50;
  XNOR2X1 mul_22_8_g325(.A (mul_22_8_n_2), .B (mul_22_8_n_50), .Y
       (out1[9]));
  ADDFX1 mul_22_8_g326(.A (mul_22_8_n_46), .B (mul_22_8_n_11), .CI
       (mul_22_8_n_9), .CO (mul_22_8_n_50), .S (out1[8]));
  XNOR2X1 mul_22_8_g327(.A (mul_22_8_n_32), .B (mul_22_8_n_48), .Y
       (out1[7]));
  AOI21X1 mul_22_8_g328(.A0 (mul_22_8_n_19), .A1 (mul_22_8_n_44), .B0
       (mul_22_8_n_24), .Y (mul_22_8_n_48));
  XNOR2X1 mul_22_8_g329(.A (mul_22_8_n_31), .B (mul_22_8_n_44), .Y
       (out1[6]));
  OAI211X1 mul_22_8_g330(.A0 (mul_22_8_n_28), .A1 (mul_22_8_n_42), .B0
       (mul_22_8_n_35), .C0 (mul_22_8_n_22), .Y (mul_22_8_n_46));
  XNOR2X1 mul_22_8_g331(.A (mul_22_8_n_30), .B (mul_22_8_n_43), .Y
       (out1[5]));
  NAND2X1 mul_22_8_g332(.A (mul_22_8_n_33), .B (mul_22_8_n_42), .Y
       (mul_22_8_n_44));
  NOR2BX1 mul_22_8_g333(.AN (mul_22_8_n_40), .B (mul_22_8_n_21), .Y
       (mul_22_8_n_43));
  NAND2BX1 mul_22_8_g334(.AN (mul_22_8_n_40), .B (mul_22_8_n_25), .Y
       (mul_22_8_n_42));
  XNOR2X1 mul_22_8_g335(.A (mul_22_8_n_29), .B (mul_22_8_n_39), .Y
       (out1[4]));
  NAND2X1 mul_22_8_g336(.A (mul_22_8_n_23), .B (mul_22_8_n_39), .Y
       (mul_22_8_n_40));
  ADDFX1 mul_22_8_g337(.A (mul_22_8_n_36), .B (mul_22_8_n_10), .CI
       (mul_22_8_n_3), .CO (mul_22_8_n_39), .S (out1[3]));
  ADDFX1 mul_22_8_g338(.A (mul_22_8_n_20), .B (mul_22_8_n_1), .CI
       (mul_22_8_n_0), .CO (mul_22_8_n_36), .S (out1[2]));
  AOI21X1 mul_22_8_g339(.A0 (mul_22_8_n_26), .A1 (mul_22_8_n_24), .B0
       (mul_22_8_n_34), .Y (mul_22_8_n_35));
  NOR2XL mul_22_8_g340(.A (mul_22_8_n_28), .B (mul_22_8_n_33), .Y
       (mul_22_8_n_34));
  AOI21X1 mul_22_8_g341(.A0 (mul_22_8_n_25), .A1 (mul_22_8_n_21), .B0
       (mul_22_8_n_18), .Y (mul_22_8_n_33));
  AND2XL mul_22_8_g342(.A (mul_22_8_n_26), .B (mul_22_8_n_22), .Y
       (mul_22_8_n_32));
  NAND2BXL mul_22_8_g343(.AN (mul_22_8_n_24), .B (mul_22_8_n_19), .Y
       (mul_22_8_n_31));
  NOR2BX1 mul_22_8_g344(.AN (mul_22_8_n_25), .B (mul_22_8_n_18), .Y
       (mul_22_8_n_30));
  NAND2BXL mul_22_8_g345(.AN (mul_22_8_n_21), .B (mul_22_8_n_23), .Y
       (mul_22_8_n_29));
  NAND2X1 mul_22_8_g346(.A (mul_22_8_n_26), .B (mul_22_8_n_19), .Y
       (mul_22_8_n_28));
  AOI21X1 mul_22_8_g347(.A0 (mul_22_8_n_14), .A1 (mul_22_8_n_7), .B0
       (mul_22_8_n_20), .Y (out1[1]));
  NAND2X1 mul_22_8_g348(.A (mul_22_8_n_6), .B (mul_22_8_n_5), .Y
       (mul_22_8_n_26));
  NAND2X1 mul_22_8_g349(.A (mul_22_8_n_17), .B (mul_22_8_n_4), .Y
       (mul_22_8_n_25));
  NOR2X1 mul_22_8_g350(.A (mul_22_8_n_8), .B (mul_22_8_n_16), .Y
       (mul_22_8_n_24));
  NAND2X1 mul_22_8_g351(.A (mul_22_8_n_13), .B (mul_22_8_n_15), .Y
       (mul_22_8_n_23));
  OR2X1 mul_22_8_g352(.A (mul_22_8_n_6), .B (mul_22_8_n_5), .Y
       (mul_22_8_n_22));
  NOR2X1 mul_22_8_g353(.A (mul_22_8_n_13), .B (mul_22_8_n_15), .Y
       (mul_22_8_n_21));
  NOR2X1 mul_22_8_g354(.A (mul_22_8_n_14), .B (mul_22_8_n_7), .Y
       (mul_22_8_n_20));
  NAND2X1 mul_22_8_g355(.A (mul_22_8_n_8), .B (mul_22_8_n_16), .Y
       (mul_22_8_n_19));
  NOR2X1 mul_22_8_g356(.A (mul_22_8_n_17), .B (mul_22_8_n_4), .Y
       (mul_22_8_n_18));
  AND2XL mul_22_8_g357(.A (in2[0]), .B (in1[0]), .Y (out1[0]));
  NAND2X1 mul_22_8_g358(.A (in2[4]), .B (in1[1]), .Y (mul_22_8_n_17));
  NAND2X1 mul_22_8_g359(.A (in2[6]), .B (in1[0]), .Y (mul_22_8_n_16));
  AND2XL mul_22_8_g360(.A (in2[8]), .B (in1[0]), .Y (mul_22_8_n_11));
  NAND2X1 mul_22_8_g361(.A (in2[4]), .B (in1[0]), .Y (mul_22_8_n_15));
  NAND2X1 mul_22_8_g362(.A (in2[0]), .B (in1[1]), .Y (mul_22_8_n_14));
  AND2XL mul_22_8_g363(.A (in2[3]), .B (in1[0]), .Y (mul_22_8_n_10));
  NAND2X1 mul_22_8_g364(.A (in2[3]), .B (in1[1]), .Y (mul_22_8_n_13));
  AND2XL mul_22_8_g365(.A (in2[7]), .B (in1[1]), .Y (mul_22_8_n_9));
  NAND2X1 mul_22_8_g366(.A (in2[5]), .B (in1[1]), .Y (mul_22_8_n_8));
  NAND2X1 mul_22_8_g367(.A (in2[1]), .B (in1[0]), .Y (mul_22_8_n_7));
  NAND2X1 mul_22_8_g368(.A (in2[6]), .B (in1[1]), .Y (mul_22_8_n_6));
  AND2XL mul_22_8_g369(.A (in2[2]), .B (in1[1]), .Y (mul_22_8_n_3));
  NAND2X1 mul_22_8_g370(.A (in2[7]), .B (in1[0]), .Y (mul_22_8_n_5));
  NAND2X1 mul_22_8_g371(.A (in2[5]), .B (in1[0]), .Y (mul_22_8_n_4));
  NAND2X1 mul_22_8_g372(.A (in2[8]), .B (in1[1]), .Y (mul_22_8_n_2));
  AND2XL mul_22_8_g373(.A (in2[2]), .B (in1[0]), .Y (mul_22_8_n_1));
  AND2XL mul_22_8_g374(.A (in2[1]), .B (in1[1]), .Y (mul_22_8_n_0));
endmodule


