`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  6 2021 05:28:20 CST (May  5 2021 21:28:20 UTC)

module Gaussian_Blur_Add_3Ux2U_4U_1(in2, in1, out1);
  input [2:0] in2;
  input [1:0] in1;
  output [3:0] out1;
  wire [2:0] in2;
  wire [1:0] in1;
  wire [3:0] out1;
  wire add_23_2_n_0, add_23_2_n_2, add_23_2_n_3, add_23_2_n_4,
       add_23_2_n_5, add_23_2_n_6, add_23_2_n_10, add_23_2_n_20;
  wire add_23_2_n_21;
  MXI2X1 add_23_2_g48(.A (add_23_2_n_3), .B (in2[2]), .S0
       (add_23_2_n_10), .Y (out1[2]));
  OAI21X2 add_23_2_g51(.A0 (add_23_2_n_4), .A1 (add_23_2_n_5), .B0
       (add_23_2_n_6), .Y (add_23_2_n_10));
  MXI2X1 add_23_2_g52(.A (add_23_2_n_20), .B (add_23_2_n_21), .S0
       (add_23_2_n_0), .Y (out1[1]));
  MXI2XL add_23_2_g55(.A (add_23_2_n_2), .B (in2[0]), .S0 (in1[0]), .Y
       (out1[0]));
  NAND2X6 add_23_2_g57(.A (in2[1]), .B (in1[1]), .Y (add_23_2_n_6));
  NOR2X4 add_23_2_g58(.A (in2[1]), .B (in1[1]), .Y (add_23_2_n_5));
  NAND2X8 add_23_2_g59(.A (in2[0]), .B (in1[0]), .Y (add_23_2_n_4));
  INVX1 add_23_2_g60(.A (in2[2]), .Y (add_23_2_n_3));
  INVX1 add_23_2_g61(.A (in2[0]), .Y (add_23_2_n_2));
  NOR2BX1 add_23_2_g2(.AN (add_23_2_n_10), .B (add_23_2_n_3), .Y
       (out1[3]));
  NOR2BX1 add_23_2_g62(.AN (add_23_2_n_6), .B (add_23_2_n_5), .Y
       (add_23_2_n_0));
  CLKINVX1 add_23_2_fopt(.A (add_23_2_n_21), .Y (add_23_2_n_20));
  CLKINVX1 add_23_2_fopt64(.A (add_23_2_n_4), .Y (add_23_2_n_21));
endmodule


