`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  6 2021 05:53:05 CST (May  5 2021 21:53:05 UTC)

module Gaussian_Blur_Add_10Ux10U_10U_4(in2, in1, out1);
  input [9:0] in2, in1;
  output [9:0] out1;
  wire [9:0] in2, in1;
  wire [9:0] out1;
  wire add_23_2_n_0, add_23_2_n_1, add_23_2_n_2, add_23_2_n_3,
       add_23_2_n_4, add_23_2_n_5, add_23_2_n_6, add_23_2_n_7;
  wire add_23_2_n_8, add_23_2_n_9, add_23_2_n_10, add_23_2_n_11,
       add_23_2_n_12, add_23_2_n_13, add_23_2_n_14, add_23_2_n_15;
  wire add_23_2_n_17, add_23_2_n_18, add_23_2_n_20, add_23_2_n_23,
       add_23_2_n_24, add_23_2_n_26, add_23_2_n_27, add_23_2_n_28;
  wire add_23_2_n_30, add_23_2_n_32, add_23_2_n_33, add_23_2_n_35;
  XNOR2X1 add_23_2_g298(.A (add_23_2_n_8), .B (add_23_2_n_35), .Y
       (out1[9]));
  ADDFX1 add_23_2_g299(.A (add_23_2_n_32), .B (in1[8]), .CI (in2[8]),
       .CO (add_23_2_n_35), .S (out1[8]));
  XNOR2X1 add_23_2_g300(.A (add_23_2_n_13), .B (add_23_2_n_33), .Y
       (out1[7]));
  OAI21X1 add_23_2_g301(.A0 (add_23_2_n_3), .A1 (add_23_2_n_28), .B0
       (add_23_2_n_7), .Y (add_23_2_n_33));
  OAI211X1 add_23_2_g302(.A0 (add_23_2_n_7), .A1 (add_23_2_n_6), .B0
       (add_23_2_n_30), .C0 (add_23_2_n_17), .Y (add_23_2_n_32));
  XNOR2X1 add_23_2_g303(.A (add_23_2_n_12), .B (add_23_2_n_28), .Y
       (out1[6]));
  AOI21X1 add_23_2_g304(.A0 (add_23_2_n_9), .A1 (add_23_2_n_27), .B0
       (add_23_2_n_4), .Y (add_23_2_n_30));
  XNOR2X1 add_23_2_g305(.A (add_23_2_n_11), .B (add_23_2_n_26), .Y
       (out1[5]));
  NOR2X1 add_23_2_g306(.A (add_23_2_n_14), .B (add_23_2_n_27), .Y
       (add_23_2_n_28));
  NOR2X1 add_23_2_g307(.A (add_23_2_n_1), .B (add_23_2_n_24), .Y
       (add_23_2_n_27));
  NAND2X1 add_23_2_g308(.A (add_23_2_n_2), .B (add_23_2_n_24), .Y
       (add_23_2_n_26));
  XNOR2X1 add_23_2_g309(.A (add_23_2_n_10), .B (add_23_2_n_23), .Y
       (out1[4]));
  NAND2BX1 add_23_2_g310(.AN (add_23_2_n_5), .B (add_23_2_n_23), .Y
       (add_23_2_n_24));
  ADDFX1 add_23_2_g311(.A (add_23_2_n_20), .B (in1[3]), .CI (in2[3]),
       .CO (add_23_2_n_23), .S (out1[3]));
  ADDFX1 add_23_2_g312(.A (add_23_2_n_18), .B (in1[2]), .CI (in2[2]),
       .CO (add_23_2_n_20), .S (out1[2]));
  ADDFX1 add_23_2_g313(.A (add_23_2_n_15), .B (in1[1]), .CI (in2[1]),
       .CO (add_23_2_n_18), .S (out1[1]));
  NAND2XL add_23_2_g314(.A (add_23_2_n_9), .B (add_23_2_n_14), .Y
       (add_23_2_n_17));
  ADDHX1 add_23_2_g315(.A (in2[0]), .B (in1[0]), .CO (add_23_2_n_15),
       .S (out1[0]));
  OAI21X1 add_23_2_g316(.A0 (add_23_2_n_2), .A1 (add_23_2_n_1), .B0
       (add_23_2_n_0), .Y (add_23_2_n_14));
  OR2XL add_23_2_g317(.A (add_23_2_n_4), .B (add_23_2_n_6), .Y
       (add_23_2_n_13));
  NOR2BX1 add_23_2_g318(.AN (add_23_2_n_7), .B (add_23_2_n_3), .Y
       (add_23_2_n_12));
  NAND2BX1 add_23_2_g319(.AN (add_23_2_n_1), .B (add_23_2_n_0), .Y
       (add_23_2_n_11));
  NAND2BX1 add_23_2_g320(.AN (add_23_2_n_5), .B (add_23_2_n_2), .Y
       (add_23_2_n_10));
  NOR2X1 add_23_2_g321(.A (add_23_2_n_6), .B (add_23_2_n_3), .Y
       (add_23_2_n_9));
  XNOR2X1 add_23_2_g322(.A (in2[9]), .B (in1[9]), .Y (add_23_2_n_8));
  NAND2X1 add_23_2_g323(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_7));
  NOR2X1 add_23_2_g324(.A (in2[7]), .B (in1[7]), .Y (add_23_2_n_6));
  NOR2X1 add_23_2_g325(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_5));
  AND2X1 add_23_2_g326(.A (in2[7]), .B (in1[7]), .Y (add_23_2_n_4));
  NOR2X1 add_23_2_g327(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_3));
  NAND2X1 add_23_2_g328(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_2));
  NOR2X1 add_23_2_g329(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_1));
  NAND2X1 add_23_2_g330(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_0));
endmodule

