`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  6 2021 05:53:15 CST (May  5 2021 21:53:15 UTC)

module Gaussian_Blur_N_Mux_11_2_0_1(in3, in2, ctrl1, out1);
  input [10:0] in3, in2;
  input ctrl1;
  output [10:0] out1;
  wire [10:0] in3, in2;
  wire ctrl1;
  wire [10:0] out1;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21;
  OAI21X4 g119(.A0 (ctrl1), .A1 (n_4), .B0 (n_17), .Y (out1[8]));
  OAI21X4 g118(.A0 (ctrl1), .A1 (n_0), .B0 (n_19), .Y (out1[9]));
  OAI21X4 g113(.A0 (ctrl1), .A1 (n_1), .B0 (n_16), .Y (out1[10]));
  OAI21X4 g112(.A0 (ctrl1), .A1 (n_2), .B0 (n_14), .Y (out1[7]));
  OAI21X4 g115(.A0 (ctrl1), .A1 (n_3), .B0 (n_18), .Y (out1[6]));
  OAI21X4 g120(.A0 (ctrl1), .A1 (n_5), .B0 (n_15), .Y (out1[5]));
  OAI21X4 g111(.A0 (ctrl1), .A1 (n_6), .B0 (n_12), .Y (out1[4]));
  OAI21X4 g114(.A0 (ctrl1), .A1 (n_9), .B0 (n_13), .Y (out1[3]));
  OAI21X4 g116(.A0 (ctrl1), .A1 (n_7), .B0 (n_21), .Y (out1[2]));
  OAI21X4 g117(.A0 (ctrl1), .A1 (n_8), .B0 (n_20), .Y (out1[1]));
  OAI21X4 g121(.A0 (ctrl1), .A1 (n_10), .B0 (n_11), .Y (out1[0]));
  NAND2X8 g126(.A (in2[2]), .B (ctrl1), .Y (n_21));
  NAND2X8 g130(.A (in2[1]), .B (ctrl1), .Y (n_20));
  NAND2X8 g122(.A (in2[9]), .B (ctrl1), .Y (n_19));
  NAND2X8 g124(.A (in2[6]), .B (ctrl1), .Y (n_18));
  NAND2X8 g131(.A (in2[8]), .B (ctrl1), .Y (n_17));
  NAND2X8 g123(.A (in2[10]), .B (ctrl1), .Y (n_16));
  NAND2X8 g132(.A (in2[5]), .B (ctrl1), .Y (n_15));
  NAND2X8 g127(.A (in2[7]), .B (ctrl1), .Y (n_14));
  NAND2X8 g128(.A (in2[3]), .B (ctrl1), .Y (n_13));
  NAND2X8 g125(.A (in2[4]), .B (ctrl1), .Y (n_12));
  NAND2X8 g129(.A (in2[0]), .B (ctrl1), .Y (n_11));
  CLKINVX4 g138(.A (in3[0]), .Y (n_10));
  CLKINVX4 g142(.A (in3[3]), .Y (n_9));
  CLKINVX4 g143(.A (in3[1]), .Y (n_8));
  CLKINVX4 g134(.A (in3[2]), .Y (n_7));
  CLKINVX4 g133(.A (in3[4]), .Y (n_6));
  CLKINVX4 g141(.A (in3[5]), .Y (n_5));
  CLKINVX4 g137(.A (in3[8]), .Y (n_4));
  CLKINVX4 g135(.A (in3[6]), .Y (n_3));
  CLKINVX4 g139(.A (in3[7]), .Y (n_2));
  CLKINVX4 g136(.A (in3[10]), .Y (n_1));
  CLKINVX4 g140(.A (in3[9]), .Y (n_0));
endmodule

