// Generated by stratus_hls 19.12-s100  (91710.131054)
// Thu May  6 05:30:13 2021
// from ../Gaussian_Blur.cpp
#include "Gaussian_Blur_ROM_9X9_filter_const.h"

struct Gaussian_Blur_ROM_9X9_filter_const;
Gaussian_Blur_ROM_9X9_filter_const::Gaussian_Blur_ROM_9X9_filter_const(sc_module_name name) : sc_module(name) 
    ,in1("in1")
    ,out1("out1")
    ,clk("clk")
    ,filter_const()
{
  CYN_ROM_INIT( sc_uint<9> , filter_const, ENUMS::CYN_HEX, "bdw_work/modules/Gaussian_Blur/BASIC/Gaussian_Blur_ROM_9X9_filter_const_1.memh", "initialize Gaussian_Blur_ROM_9X9_filter_const" ); 
  SC_METHOD(Gaussian_Blur_ROM_9X9_filter_const_filter_const_thread_1);
  sensitive << clk.pos();
  dont_initialize();

}
void Gaussian_Blur_ROM_9X9_filter_const::Gaussian_Blur_ROM_9X9_filter_const_filter_const_thread_1(){
  if ( (/*imp*/sc_uint<1>)(in1.read() < ((/*imp*/sc_uint<4> )(9ULL))) ) {
    out1 = (sc_uint<9> ) ((filter_const)[in1.read()]);
  } 
}
