`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  6 2021 05:33:21 CST (May  5 2021 21:33:21 UTC)

module Gaussian_Blur_Add2Add2u2u8Mul2i258u2_4(in3, in2, in1, out1);
  input [1:0] in3, in1;
  input [7:0] in2;
  output [9:0] out1;
  wire [1:0] in3, in1;
  wire [7:0] in2;
  wire [9:0] out1;
  wire csa_tree_add_32_2_groupi_n_0, csa_tree_add_32_2_groupi_n_1,
       csa_tree_add_32_2_groupi_n_2, csa_tree_add_32_2_groupi_n_4,
       csa_tree_add_32_2_groupi_n_5, csa_tree_add_32_2_groupi_n_6,
       csa_tree_add_32_2_groupi_n_8, csa_tree_add_32_2_groupi_n_11;
  wire csa_tree_add_32_2_groupi_n_12, csa_tree_add_32_2_groupi_n_14,
       csa_tree_add_32_2_groupi_n_16, csa_tree_add_32_2_groupi_n_18,
       csa_tree_add_32_2_groupi_n_20;
  XNOR2X1 csa_tree_add_32_2_groupi_g152(.A (in3[1]), .B
       (csa_tree_add_32_2_groupi_n_20), .Y (out1[9]));
  XNOR2X1 csa_tree_add_32_2_groupi_g153(.A (in3[0]), .B
       (csa_tree_add_32_2_groupi_n_18), .Y (out1[8]));
  NAND2BX1 csa_tree_add_32_2_groupi_g154(.AN
       (csa_tree_add_32_2_groupi_n_18), .B (in3[0]), .Y
       (csa_tree_add_32_2_groupi_n_20));
  XNOR2X1 csa_tree_add_32_2_groupi_g155(.A (in2[7]), .B
       (csa_tree_add_32_2_groupi_n_16), .Y (out1[7]));
  NAND2BX1 csa_tree_add_32_2_groupi_g156(.AN
       (csa_tree_add_32_2_groupi_n_16), .B (in2[7]), .Y
       (csa_tree_add_32_2_groupi_n_18));
  XNOR2X1 csa_tree_add_32_2_groupi_g157(.A (in2[6]), .B
       (csa_tree_add_32_2_groupi_n_14), .Y (out1[6]));
  NAND2BX1 csa_tree_add_32_2_groupi_g158(.AN
       (csa_tree_add_32_2_groupi_n_14), .B (in2[6]), .Y
       (csa_tree_add_32_2_groupi_n_16));
  XNOR2X1 csa_tree_add_32_2_groupi_g159(.A (in2[5]), .B
       (csa_tree_add_32_2_groupi_n_12), .Y (out1[5]));
  NAND2BX1 csa_tree_add_32_2_groupi_g160(.AN
       (csa_tree_add_32_2_groupi_n_12), .B (in2[5]), .Y
       (csa_tree_add_32_2_groupi_n_14));
  XOR2XL csa_tree_add_32_2_groupi_g161(.A (in2[4]), .B
       (csa_tree_add_32_2_groupi_n_11), .Y (out1[4]));
  NAND2X1 csa_tree_add_32_2_groupi_g162(.A (in2[4]), .B
       (csa_tree_add_32_2_groupi_n_11), .Y
       (csa_tree_add_32_2_groupi_n_12));
  ADDFX1 csa_tree_add_32_2_groupi_g163(.A
       (csa_tree_add_32_2_groupi_n_8), .B (in2[3]), .CI
       (csa_tree_add_32_2_groupi_n_4), .CO
       (csa_tree_add_32_2_groupi_n_11), .S (out1[3]));
  ADDFX1 csa_tree_add_32_2_groupi_g164(.A
       (csa_tree_add_32_2_groupi_n_6), .B
       (csa_tree_add_32_2_groupi_n_0), .CI
       (csa_tree_add_32_2_groupi_n_5), .CO
       (csa_tree_add_32_2_groupi_n_8), .S (out1[2]));
  ADDFX1 csa_tree_add_32_2_groupi_g165(.A
       (csa_tree_add_32_2_groupi_n_2), .B (in1[1]), .CI
       (csa_tree_add_32_2_groupi_n_1), .CO
       (csa_tree_add_32_2_groupi_n_6), .S (out1[1]));
  ADDHX1 csa_tree_add_32_2_groupi_g166(.A (in3[1]), .B (in2[2]), .CO
       (csa_tree_add_32_2_groupi_n_4), .S
       (csa_tree_add_32_2_groupi_n_5));
  ADDHX1 csa_tree_add_32_2_groupi_g167(.A (in2[0]), .B (in1[0]), .CO
       (csa_tree_add_32_2_groupi_n_2), .S (out1[0]));
  ADDHX1 csa_tree_add_32_2_groupi_g168(.A (in3[0]), .B (in2[1]), .CO
       (csa_tree_add_32_2_groupi_n_0), .S
       (csa_tree_add_32_2_groupi_n_1));
endmodule

