`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  6 2021 05:33:45 CST (May  5 2021 21:33:45 UTC)

module Gaussian_Blur_R10_10Add3s9s9s9_1(in3, in2, in1, out1);
  input [8:0] in3, in2, in1;
  output out1;
  wire [8:0] in3, in2, in1;
  wire out1;
  wire csa_tree_add_28_2_groupi_n_0, csa_tree_add_28_2_groupi_n_1,
       csa_tree_add_28_2_groupi_n_2, csa_tree_add_28_2_groupi_n_3,
       csa_tree_add_28_2_groupi_n_4, csa_tree_add_28_2_groupi_n_5,
       csa_tree_add_28_2_groupi_n_7, csa_tree_add_28_2_groupi_n_8;
  wire csa_tree_add_28_2_groupi_n_9, csa_tree_add_28_2_groupi_n_10,
       csa_tree_add_28_2_groupi_n_11, csa_tree_add_28_2_groupi_n_12,
       csa_tree_add_28_2_groupi_n_13, csa_tree_add_28_2_groupi_n_14,
       csa_tree_add_28_2_groupi_n_15, csa_tree_add_28_2_groupi_n_16;
  wire csa_tree_add_28_2_groupi_n_17, csa_tree_add_28_2_groupi_n_18,
       csa_tree_add_28_2_groupi_n_19, csa_tree_add_28_2_groupi_n_20,
       csa_tree_add_28_2_groupi_n_21, csa_tree_add_28_2_groupi_n_22,
       csa_tree_add_28_2_groupi_n_23, csa_tree_add_28_2_groupi_n_24;
  wire csa_tree_add_28_2_groupi_n_25, csa_tree_add_28_2_groupi_n_26,
       csa_tree_add_28_2_groupi_n_27, csa_tree_add_28_2_groupi_n_28,
       csa_tree_add_28_2_groupi_n_29, csa_tree_add_28_2_groupi_n_30,
       csa_tree_add_28_2_groupi_n_31, csa_tree_add_28_2_groupi_n_32;
  wire csa_tree_add_28_2_groupi_n_33, csa_tree_add_28_2_groupi_n_34,
       csa_tree_add_28_2_groupi_n_36, csa_tree_add_28_2_groupi_n_37,
       csa_tree_add_28_2_groupi_n_38, csa_tree_add_28_2_groupi_n_39,
       csa_tree_add_28_2_groupi_n_41, csa_tree_add_28_2_groupi_n_42;
  wire csa_tree_add_28_2_groupi_n_43, csa_tree_add_28_2_groupi_n_44,
       csa_tree_add_28_2_groupi_n_45, csa_tree_add_28_2_groupi_n_46,
       csa_tree_add_28_2_groupi_n_47, csa_tree_add_28_2_groupi_n_48,
       csa_tree_add_28_2_groupi_n_49, csa_tree_add_28_2_groupi_n_50;
  wire csa_tree_add_28_2_groupi_n_51, csa_tree_add_28_2_groupi_n_52,
       csa_tree_add_28_2_groupi_n_53, csa_tree_add_28_2_groupi_n_54,
       csa_tree_add_28_2_groupi_n_55, csa_tree_add_28_2_groupi_n_56,
       csa_tree_add_28_2_groupi_n_57, csa_tree_add_28_2_groupi_n_58;
  wire csa_tree_add_28_2_groupi_n_59, csa_tree_add_28_2_groupi_n_60,
       csa_tree_add_28_2_groupi_n_61, csa_tree_add_28_2_groupi_n_62,
       csa_tree_add_28_2_groupi_n_91, csa_tree_add_28_2_groupi_n_92,
       csa_tree_add_28_2_groupi_n_94;
  AOI21X2 csa_tree_add_28_2_groupi_g616(.A0
       (csa_tree_add_28_2_groupi_n_51), .A1
       (csa_tree_add_28_2_groupi_n_62), .B0
       (csa_tree_add_28_2_groupi_n_57), .Y (out1));
  NAND2X1 csa_tree_add_28_2_groupi_g617(.A
       (csa_tree_add_28_2_groupi_n_61), .B
       (csa_tree_add_28_2_groupi_n_60), .Y
       (csa_tree_add_28_2_groupi_n_62));
  NOR2X1 csa_tree_add_28_2_groupi_g618(.A
       (csa_tree_add_28_2_groupi_n_55), .B
       (csa_tree_add_28_2_groupi_n_58), .Y
       (csa_tree_add_28_2_groupi_n_61));
  NAND2X1 csa_tree_add_28_2_groupi_g619(.A
       (csa_tree_add_28_2_groupi_n_5), .B
       (csa_tree_add_28_2_groupi_n_59), .Y
       (csa_tree_add_28_2_groupi_n_60));
  NAND2X1 csa_tree_add_28_2_groupi_g620(.A
       (csa_tree_add_28_2_groupi_n_50), .B
       (csa_tree_add_28_2_groupi_n_53), .Y
       (csa_tree_add_28_2_groupi_n_59));
  NOR2X1 csa_tree_add_28_2_groupi_g621(.A
       (csa_tree_add_28_2_groupi_n_45), .B
       (csa_tree_add_28_2_groupi_n_54), .Y
       (csa_tree_add_28_2_groupi_n_58));
  OAI2BB1X1 csa_tree_add_28_2_groupi_g622(.A0N
       (csa_tree_add_28_2_groupi_n_12), .A1N
       (csa_tree_add_28_2_groupi_n_22), .B0
       (csa_tree_add_28_2_groupi_n_56), .Y
       (csa_tree_add_28_2_groupi_n_57));
  NAND3BXL csa_tree_add_28_2_groupi_g623(.AN
       (csa_tree_add_28_2_groupi_n_48), .B
       (csa_tree_add_28_2_groupi_n_25), .C
       (csa_tree_add_28_2_groupi_n_20), .Y
       (csa_tree_add_28_2_groupi_n_56));
  OAI31X1 csa_tree_add_28_2_groupi_g625(.A0
       (csa_tree_add_28_2_groupi_n_91), .A1
       (csa_tree_add_28_2_groupi_n_27), .A2
       (csa_tree_add_28_2_groupi_n_94), .B0
       (csa_tree_add_28_2_groupi_n_3), .Y
       (csa_tree_add_28_2_groupi_n_55));
  AOI21X1 csa_tree_add_28_2_groupi_g626(.A0
       (csa_tree_add_28_2_groupi_n_4), .A1
       (csa_tree_add_28_2_groupi_n_0), .B0
       (csa_tree_add_28_2_groupi_n_49), .Y
       (csa_tree_add_28_2_groupi_n_54));
  NAND2X1 csa_tree_add_28_2_groupi_g627(.A
       (csa_tree_add_28_2_groupi_n_41), .B
       (csa_tree_add_28_2_groupi_n_52), .Y
       (csa_tree_add_28_2_groupi_n_53));
  AOI21X1 csa_tree_add_28_2_groupi_g628(.A0
       (csa_tree_add_28_2_groupi_n_24), .A1
       (csa_tree_add_28_2_groupi_n_36), .B0
       (csa_tree_add_28_2_groupi_n_38), .Y
       (csa_tree_add_28_2_groupi_n_52));
  NOR2X1 csa_tree_add_28_2_groupi_g629(.A
       (csa_tree_add_28_2_groupi_n_48), .B
       (csa_tree_add_28_2_groupi_n_46), .Y
       (csa_tree_add_28_2_groupi_n_51));
  AOI21X2 csa_tree_add_28_2_groupi_g630(.A0
       (csa_tree_add_28_2_groupi_n_1), .A1
       (csa_tree_add_28_2_groupi_n_39), .B0
       (csa_tree_add_28_2_groupi_n_42), .Y
       (csa_tree_add_28_2_groupi_n_50));
  AND2XL csa_tree_add_28_2_groupi_g631(.A
       (csa_tree_add_28_2_groupi_n_43), .B
       (csa_tree_add_28_2_groupi_n_28), .Y
       (csa_tree_add_28_2_groupi_n_49));
  NOR2X1 csa_tree_add_28_2_groupi_g633(.A
       (csa_tree_add_28_2_groupi_n_12), .B
       (csa_tree_add_28_2_groupi_n_22), .Y
       (csa_tree_add_28_2_groupi_n_48));
  NOR2X1 csa_tree_add_28_2_groupi_g636(.A
       (csa_tree_add_28_2_groupi_n_31), .B
       (csa_tree_add_28_2_groupi_n_44), .Y
       (csa_tree_add_28_2_groupi_n_47));
  NOR2X1 csa_tree_add_28_2_groupi_g637(.A
       (csa_tree_add_28_2_groupi_n_20), .B
       (csa_tree_add_28_2_groupi_n_25), .Y
       (csa_tree_add_28_2_groupi_n_46));
  NAND2X1 csa_tree_add_28_2_groupi_g638(.A
       (csa_tree_add_28_2_groupi_n_37), .B
       (csa_tree_add_28_2_groupi_n_2), .Y
       (csa_tree_add_28_2_groupi_n_45));
  ADDFXL csa_tree_add_28_2_groupi_g640(.A (in2[4]), .B (in3[4]), .CI
       (in1[4]), .CO (csa_tree_add_28_2_groupi_n_43), .S
       (csa_tree_add_28_2_groupi_n_44));
  AND2XL csa_tree_add_28_2_groupi_g641(.A
       (csa_tree_add_28_2_groupi_n_29), .B
       (csa_tree_add_28_2_groupi_n_32), .Y
       (csa_tree_add_28_2_groupi_n_42));
  OR2XL csa_tree_add_28_2_groupi_g642(.A
       (csa_tree_add_28_2_groupi_n_10), .B
       (csa_tree_add_28_2_groupi_n_30), .Y
       (csa_tree_add_28_2_groupi_n_41));
  INVX1 csa_tree_add_28_2_groupi_g647(.A
       (csa_tree_add_28_2_groupi_n_38), .Y
       (csa_tree_add_28_2_groupi_n_39));
  NOR2X2 csa_tree_add_28_2_groupi_g648(.A
       (csa_tree_add_28_2_groupi_n_29), .B
       (csa_tree_add_28_2_groupi_n_32), .Y
       (csa_tree_add_28_2_groupi_n_38));
  NAND2X1 csa_tree_add_28_2_groupi_g649(.A
       (csa_tree_add_28_2_groupi_n_27), .B
       (csa_tree_add_28_2_groupi_n_92), .Y
       (csa_tree_add_28_2_groupi_n_37));
  NAND3BXL csa_tree_add_28_2_groupi_g650(.AN
       (csa_tree_add_28_2_groupi_n_19), .B
       (csa_tree_add_28_2_groupi_n_13), .C
       (csa_tree_add_28_2_groupi_n_23), .Y
       (csa_tree_add_28_2_groupi_n_36));
  ADDFHXL csa_tree_add_28_2_groupi_g654(.A (in3[6]), .B (in2[6]), .CI
       (in1[6]), .CO (csa_tree_add_28_2_groupi_n_34), .S
       (csa_tree_add_28_2_groupi_n_33));
  ADDFHXL csa_tree_add_28_2_groupi_g655(.A (in1[3]), .B (in2[3]), .CI
       (in3[3]), .CO (csa_tree_add_28_2_groupi_n_31), .S
       (csa_tree_add_28_2_groupi_n_32));
  ADDFXL csa_tree_add_28_2_groupi_g657(.A (in3[2]), .B (in2[2]), .CI
       (in1[2]), .CO (csa_tree_add_28_2_groupi_n_29), .S
       (csa_tree_add_28_2_groupi_n_30));
  INVX1 csa_tree_add_28_2_groupi_g659(.A
       (csa_tree_add_28_2_groupi_n_26), .Y
       (csa_tree_add_28_2_groupi_n_27));
  ADDFXL csa_tree_add_28_2_groupi_g660(.A (in3[5]), .B (in2[5]), .CI
       (in1[5]), .CO (csa_tree_add_28_2_groupi_n_26), .S
       (csa_tree_add_28_2_groupi_n_28));
  OAI21X1 csa_tree_add_28_2_groupi_g661(.A0 (in2[8]), .A1
       (csa_tree_add_28_2_groupi_n_17), .B0
       (csa_tree_add_28_2_groupi_n_22), .Y
       (csa_tree_add_28_2_groupi_n_25));
  NAND2X1 csa_tree_add_28_2_groupi_g662(.A (in3[1]), .B
       (csa_tree_add_28_2_groupi_n_15), .Y
       (csa_tree_add_28_2_groupi_n_24));
  NAND3BXL csa_tree_add_28_2_groupi_g663(.AN (in3[1]), .B
       (csa_tree_add_28_2_groupi_n_14), .C
       (csa_tree_add_28_2_groupi_n_11), .Y
       (csa_tree_add_28_2_groupi_n_23));
  NAND2X1 csa_tree_add_28_2_groupi_g664(.A (in2[8]), .B
       (csa_tree_add_28_2_groupi_n_17), .Y
       (csa_tree_add_28_2_groupi_n_22));
  CLKXOR2X1 csa_tree_add_28_2_groupi_g665(.A (in2[7]), .B
       (csa_tree_add_28_2_groupi_n_16), .Y
       (csa_tree_add_28_2_groupi_n_21));
  OAI2BB1X1 csa_tree_add_28_2_groupi_g666(.A0N (in1[7]), .A1N (in2[7]),
       .B0 (csa_tree_add_28_2_groupi_n_18), .Y
       (csa_tree_add_28_2_groupi_n_20));
  AOI21X1 csa_tree_add_28_2_groupi_g667(.A0 (in1[0]), .A1 (in2[0]), .B0
       (in3[0]), .Y (csa_tree_add_28_2_groupi_n_19));
  OAI21X1 csa_tree_add_28_2_groupi_g668(.A0 (in1[7]), .A1 (in2[7]), .B0
       (in3[7]), .Y (csa_tree_add_28_2_groupi_n_18));
  XNOR2X1 csa_tree_add_28_2_groupi_g669(.A (in1[8]), .B (in3[8]), .Y
       (csa_tree_add_28_2_groupi_n_17));
  MXI2XL csa_tree_add_28_2_groupi_g670(.A (in1[7]), .B
       (csa_tree_add_28_2_groupi_n_7), .S0 (in3[7]), .Y
       (csa_tree_add_28_2_groupi_n_16));
  NAND2X1 csa_tree_add_28_2_groupi_g671(.A
       (csa_tree_add_28_2_groupi_n_14), .B
       (csa_tree_add_28_2_groupi_n_11), .Y
       (csa_tree_add_28_2_groupi_n_15));
  NAND2X1 csa_tree_add_28_2_groupi_g672(.A (in2[1]), .B
       (csa_tree_add_28_2_groupi_n_9), .Y
       (csa_tree_add_28_2_groupi_n_14));
  OR2XL csa_tree_add_28_2_groupi_g673(.A (in1[0]), .B (in2[0]), .Y
       (csa_tree_add_28_2_groupi_n_13));
  NOR2X1 csa_tree_add_28_2_groupi_g674(.A (in1[8]), .B (in3[8]), .Y
       (csa_tree_add_28_2_groupi_n_12));
  NAND2X1 csa_tree_add_28_2_groupi_g675(.A (in1[1]), .B
       (csa_tree_add_28_2_groupi_n_8), .Y
       (csa_tree_add_28_2_groupi_n_11));
  NOR2X1 csa_tree_add_28_2_groupi_g676(.A
       (csa_tree_add_28_2_groupi_n_9), .B
       (csa_tree_add_28_2_groupi_n_8), .Y
       (csa_tree_add_28_2_groupi_n_10));
  INVX1 csa_tree_add_28_2_groupi_g677(.A (in1[1]), .Y
       (csa_tree_add_28_2_groupi_n_9));
  INVX1 csa_tree_add_28_2_groupi_g678(.A (in2[1]), .Y
       (csa_tree_add_28_2_groupi_n_8));
  CLKINVX2 csa_tree_add_28_2_groupi_g679(.A (in1[7]), .Y
       (csa_tree_add_28_2_groupi_n_7));
  NOR3BX1 csa_tree_add_28_2_groupi_g2(.AN
       (csa_tree_add_28_2_groupi_n_0), .B
       (csa_tree_add_28_2_groupi_n_47), .C
       (csa_tree_add_28_2_groupi_n_45), .Y
       (csa_tree_add_28_2_groupi_n_5));
  AND2XL csa_tree_add_28_2_groupi_g680(.A
       (csa_tree_add_28_2_groupi_n_31), .B
       (csa_tree_add_28_2_groupi_n_44), .Y
       (csa_tree_add_28_2_groupi_n_4));
  NAND2BX1 csa_tree_add_28_2_groupi_g681(.AN
       (csa_tree_add_28_2_groupi_n_21), .B
       (csa_tree_add_28_2_groupi_n_34), .Y
       (csa_tree_add_28_2_groupi_n_3));
  NAND2BX1 csa_tree_add_28_2_groupi_g682(.AN
       (csa_tree_add_28_2_groupi_n_34), .B
       (csa_tree_add_28_2_groupi_n_21), .Y
       (csa_tree_add_28_2_groupi_n_2));
  AND2XL csa_tree_add_28_2_groupi_g683(.A
       (csa_tree_add_28_2_groupi_n_10), .B
       (csa_tree_add_28_2_groupi_n_30), .Y
       (csa_tree_add_28_2_groupi_n_1));
  OR2XL csa_tree_add_28_2_groupi_g684(.A
       (csa_tree_add_28_2_groupi_n_43), .B
       (csa_tree_add_28_2_groupi_n_28), .Y
       (csa_tree_add_28_2_groupi_n_0));
  INVXL csa_tree_add_28_2_groupi_fopt(.A
       (csa_tree_add_28_2_groupi_n_33), .Y
       (csa_tree_add_28_2_groupi_n_91));
  CLKINVX1 csa_tree_add_28_2_groupi_fopt685(.A
       (csa_tree_add_28_2_groupi_n_33), .Y
       (csa_tree_add_28_2_groupi_n_92));
  INVXL csa_tree_add_28_2_groupi_fopt686(.A
       (csa_tree_add_28_2_groupi_n_2), .Y
       (csa_tree_add_28_2_groupi_n_94));
endmodule

