`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  6 2021 05:28:47 CST (May  5 2021 21:28:47 UTC)

module Gaussian_Blur_Mul_9Ux2U_10U_1(in2, in1, out1);
  input [8:0] in2;
  input [1:0] in1;
  output [9:0] out1;
  wire [8:0] in2;
  wire [1:0] in1;
  wire [9:0] out1;
  wire mul_22_8_n_1, mul_22_8_n_5, mul_22_8_n_7, mul_22_8_n_8,
       mul_22_8_n_9, mul_22_8_n_10, mul_22_8_n_11, mul_22_8_n_12;
  wire mul_22_8_n_13, mul_22_8_n_14, mul_22_8_n_15, mul_22_8_n_16,
       mul_22_8_n_17, mul_22_8_n_18, mul_22_8_n_19, mul_22_8_n_20;
  wire mul_22_8_n_21, mul_22_8_n_22, mul_22_8_n_23, mul_22_8_n_24,
       mul_22_8_n_25, mul_22_8_n_26, mul_22_8_n_27, mul_22_8_n_28;
  wire mul_22_8_n_29, mul_22_8_n_30, mul_22_8_n_31, mul_22_8_n_32,
       mul_22_8_n_33, mul_22_8_n_34, mul_22_8_n_35, mul_22_8_n_36;
  wire mul_22_8_n_37, mul_22_8_n_38, mul_22_8_n_39, mul_22_8_n_41,
       mul_22_8_n_42, mul_22_8_n_43, mul_22_8_n_44, mul_22_8_n_45;
  wire mul_22_8_n_46, mul_22_8_n_47, mul_22_8_n_48, mul_22_8_n_49,
       mul_22_8_n_50, mul_22_8_n_51, mul_22_8_n_52, mul_22_8_n_53;
  wire mul_22_8_n_54, mul_22_8_n_55, mul_22_8_n_56, mul_22_8_n_57,
       mul_22_8_n_59, mul_22_8_n_61, mul_22_8_n_62, mul_22_8_n_63;
  wire mul_22_8_n_64, mul_22_8_n_65, mul_22_8_n_66, mul_22_8_n_67,
       mul_22_8_n_68, mul_22_8_n_69, mul_22_8_n_70, mul_22_8_n_72;
  wire mul_22_8_n_74, mul_22_8_n_87, mul_22_8_n_89, mul_22_8_n_90,
       mul_22_8_n_91, mul_22_8_n_93, mul_22_8_n_95, mul_22_8_n_96;
  wire mul_22_8_n_97, mul_22_8_n_98, mul_22_8_n_101, mul_22_8_n_102,
       mul_22_8_n_103, mul_22_8_n_106;
  MXI2XL mul_22_8_g369(.A (mul_22_8_n_52), .B (mul_22_8_n_51), .S0
       (mul_22_8_n_74), .Y (out1[7]));
  NOR2X1 mul_22_8_g370(.A (mul_22_8_n_36), .B (mul_22_8_n_70), .Y
       (mul_22_8_n_74));
  MXI2XL mul_22_8_g371(.A (mul_22_8_n_48), .B (mul_22_8_n_49), .S0
       (mul_22_8_n_93), .Y (out1[6]));
  NOR2X1 mul_22_8_g373(.A (mul_22_8_n_32), .B (mul_22_8_n_69), .Y
       (mul_22_8_n_72));
  MXI2XL mul_22_8_g374(.A (mul_22_8_n_53), .B (mul_22_8_n_54), .S0
       (mul_22_8_n_87), .Y (out1[8]));
  NOR2X1 mul_22_8_g375(.A (mul_22_8_n_28), .B (mul_22_8_n_5), .Y
       (mul_22_8_n_70));
  NOR2X1 mul_22_8_g376(.A (mul_22_8_n_30), .B (mul_22_8_n_68), .Y
       (mul_22_8_n_69));
  NOR2X1 mul_22_8_g377(.A (mul_22_8_n_61), .B (mul_22_8_n_64), .Y
       (mul_22_8_n_68));
  NOR2X1 mul_22_8_g379(.A (mul_22_8_n_35), .B (mul_22_8_n_65), .Y
       (mul_22_8_n_67));
  NOR2X1 mul_22_8_g382(.A (mul_22_8_n_106), .B (mul_22_8_n_62), .Y
       (mul_22_8_n_66));
  NOR2BX1 mul_22_8_g383(.AN (mul_22_8_n_29), .B (mul_22_8_n_102), .Y
       (mul_22_8_n_65));
  NOR2X2 mul_22_8_g384(.A (mul_22_8_n_57), .B (mul_22_8_n_62), .Y
       (mul_22_8_n_64));
  AOI21X1 mul_22_8_g385(.A0 (mul_22_8_n_37), .A1 (mul_22_8_n_97), .B0
       (mul_22_8_n_90), .Y (mul_22_8_n_63));
  NOR2X4 mul_22_8_g386(.A (mul_22_8_n_59), .B (mul_22_8_n_1), .Y
       (mul_22_8_n_62));
  OAI21X1 mul_22_8_g387(.A0 (mul_22_8_n_45), .A1 (mul_22_8_n_55), .B0
       (mul_22_8_n_56), .Y (mul_22_8_n_61));
  MXI2XL mul_22_8_g388(.A (mul_22_8_n_97), .B (mul_22_8_n_96), .S0
       (mul_22_8_n_46), .Y (out1[2]));
  NOR2X2 mul_22_8_g389(.A (mul_22_8_n_98), .B (mul_22_8_n_42), .Y
       (mul_22_8_n_59));
  OR2XL mul_22_8_g391(.A (mul_22_8_n_45), .B (mul_22_8_n_44), .Y
       (mul_22_8_n_57));
  AOI21X1 mul_22_8_g392(.A0 (mul_22_8_n_26), .A1 (mul_22_8_n_36), .B0
       (mul_22_8_n_38), .Y (mul_22_8_n_56));
  AOI21X1 mul_22_8_g394(.A0 (mul_22_8_n_34), .A1 (mul_22_8_n_35), .B0
       (mul_22_8_n_31), .Y (mul_22_8_n_55));
  INVX1 mul_22_8_g396(.A (mul_22_8_n_53), .Y (mul_22_8_n_54));
  INVX1 mul_22_8_g397(.A (mul_22_8_n_51), .Y (mul_22_8_n_52));
  INVX1 mul_22_8_g399(.A (mul_22_8_n_48), .Y (mul_22_8_n_49));
  NAND2BXL mul_22_8_g401(.AN (mul_22_8_n_89), .B (mul_22_8_n_37), .Y
       (mul_22_8_n_46));
  NOR2X1 mul_22_8_g402(.A (mul_22_8_n_30), .B (mul_22_8_n_32), .Y
       (mul_22_8_n_53));
  NAND2BX1 mul_22_8_g403(.AN (mul_22_8_n_38), .B (mul_22_8_n_26), .Y
       (mul_22_8_n_51));
  NAND2BX1 mul_22_8_g404(.AN (mul_22_8_n_39), .B (mul_22_8_n_24), .Y
       (mul_22_8_n_50));
  NOR2X1 mul_22_8_g405(.A (mul_22_8_n_28), .B (mul_22_8_n_36), .Y
       (mul_22_8_n_48));
  NAND2BX1 mul_22_8_g406(.AN (mul_22_8_n_31), .B (mul_22_8_n_34), .Y
       (mul_22_8_n_47));
  NAND2X2 mul_22_8_g408(.A (mul_22_8_n_24), .B (mul_22_8_n_37), .Y
       (mul_22_8_n_42));
  NAND2X4 mul_22_8_g409(.A (mul_22_8_n_25), .B (mul_22_8_n_24), .Y
       (mul_22_8_n_41));
  AOI21X1 mul_22_8_g410(.A0 (mul_22_8_n_10), .A1 (mul_22_8_n_23), .B0
       (mul_22_8_n_95), .Y (out1[1]));
  NAND2X2 mul_22_8_g411(.A (mul_22_8_n_26), .B (mul_22_8_n_27), .Y
       (mul_22_8_n_45));
  NAND2X1 mul_22_8_g412(.A (mul_22_8_n_34), .B (mul_22_8_n_29), .Y
       (mul_22_8_n_44));
  NOR2BX1 mul_22_8_g413(.AN (mul_22_8_n_29), .B (mul_22_8_n_35), .Y
       (mul_22_8_n_43));
  NOR2X1 mul_22_8_g415(.A (mul_22_8_n_7), .B (mul_22_8_n_12), .Y
       (mul_22_8_n_39));
  NOR2X1 mul_22_8_g416(.A (mul_22_8_n_11), .B (mul_22_8_n_15), .Y
       (mul_22_8_n_38));
  NAND2X2 mul_22_8_g417(.A (mul_22_8_n_17), .B (mul_22_8_n_9), .Y
       (mul_22_8_n_37));
  NOR2X1 mul_22_8_g418(.A (mul_22_8_n_20), .B (mul_22_8_n_18), .Y
       (mul_22_8_n_36));
  NOR2X2 mul_22_8_g419(.A (mul_22_8_n_16), .B (mul_22_8_n_22), .Y
       (mul_22_8_n_35));
  NAND2X2 mul_22_8_g420(.A (mul_22_8_n_21), .B (mul_22_8_n_8), .Y
       (mul_22_8_n_34));
  NOR2X2 mul_22_8_g421(.A (mul_22_8_n_10), .B (mul_22_8_n_23), .Y
       (mul_22_8_n_33));
  INVX1 mul_22_8_g422(.A (mul_22_8_n_27), .Y (mul_22_8_n_28));
  NOR2X1 mul_22_8_g423(.A (mul_22_8_n_14), .B (mul_22_8_n_13), .Y
       (mul_22_8_n_32));
  NOR2X1 mul_22_8_g424(.A (mul_22_8_n_21), .B (mul_22_8_n_8), .Y
       (mul_22_8_n_31));
  AND2X1 mul_22_8_g425(.A (mul_22_8_n_14), .B (mul_22_8_n_13), .Y
       (mul_22_8_n_30));
  NAND2X2 mul_22_8_g426(.A (mul_22_8_n_16), .B (mul_22_8_n_22), .Y
       (mul_22_8_n_29));
  NAND2X2 mul_22_8_g427(.A (mul_22_8_n_20), .B (mul_22_8_n_18), .Y
       (mul_22_8_n_27));
  NAND2X4 mul_22_8_g428(.A (mul_22_8_n_11), .B (mul_22_8_n_15), .Y
       (mul_22_8_n_26));
  NOR2X2 mul_22_8_g429(.A (mul_22_8_n_17), .B (mul_22_8_n_9), .Y
       (mul_22_8_n_25));
  NAND2X4 mul_22_8_g430(.A (mul_22_8_n_7), .B (mul_22_8_n_12), .Y
       (mul_22_8_n_24));
  NAND2X2 mul_22_8_g432(.A (in2[1]), .B (in1[0]), .Y (mul_22_8_n_23));
  NAND2X4 mul_22_8_g433(.A (in2[4]), .B (in1[0]), .Y (mul_22_8_n_22));
  NAND2X8 mul_22_8_g434(.A (in2[4]), .B (in1[1]), .Y (mul_22_8_n_21));
  NAND2X4 mul_22_8_g435(.A (in2[5]), .B (in1[1]), .Y (mul_22_8_n_20));
  NAND2X1 mul_22_8_g436(.A (in2[8]), .B (in1[1]), .Y (mul_22_8_n_19));
  NAND2X4 mul_22_8_g437(.A (in2[6]), .B (in1[0]), .Y (mul_22_8_n_18));
  NAND2X6 mul_22_8_g438(.A (in2[1]), .B (in1[1]), .Y (mul_22_8_n_17));
  NAND2X4 mul_22_8_g439(.A (in2[3]), .B (in1[1]), .Y (mul_22_8_n_16));
  NAND2X6 mul_22_8_g440(.A (in2[7]), .B (in1[0]), .Y (mul_22_8_n_15));
  AND2XL mul_22_8_g441(.A (in2[0]), .B (in1[0]), .Y (out1[0]));
  NAND2X1 mul_22_8_g442(.A (in2[7]), .B (in1[1]), .Y (mul_22_8_n_14));
  NAND2X1 mul_22_8_g443(.A (in2[8]), .B (in1[0]), .Y (mul_22_8_n_13));
  NAND2X6 mul_22_8_g444(.A (in2[3]), .B (in1[0]), .Y (mul_22_8_n_12));
  NAND2X8 mul_22_8_g445(.A (in2[6]), .B (in1[1]), .Y (mul_22_8_n_11));
  NAND2X4 mul_22_8_g446(.A (in2[0]), .B (in1[1]), .Y (mul_22_8_n_10));
  NAND2X4 mul_22_8_g447(.A (in2[2]), .B (in1[0]), .Y (mul_22_8_n_9));
  NAND2X6 mul_22_8_g448(.A (in2[5]), .B (in1[0]), .Y (mul_22_8_n_8));
  NAND2X8 mul_22_8_g449(.A (in2[2]), .B (in1[1]), .Y (mul_22_8_n_7));
  NOR2BX1 mul_22_8_g2(.AN (mul_22_8_n_55), .B (mul_22_8_n_66), .Y
       (mul_22_8_n_5));
  XOR2XL mul_22_8_g450(.A (mul_22_8_n_50), .B (mul_22_8_n_63), .Y
       (out1[3]));
  CLKXOR2X1 mul_22_8_g451(.A (mul_22_8_n_47), .B (mul_22_8_n_67), .Y
       (out1[5]));
  XNOR2X1 mul_22_8_g452(.A (mul_22_8_n_43), .B (mul_22_8_n_101), .Y
       (out1[4]));
  NAND2BX4 mul_22_8_g453(.AN (mul_22_8_n_39), .B (mul_22_8_n_41), .Y
       (mul_22_8_n_1));
  CLKXOR2X1 mul_22_8_g454(.A (mul_22_8_n_19), .B (mul_22_8_n_72), .Y
       (out1[9]));
  BUFX2 mul_22_8_fopt(.A (mul_22_8_n_68), .Y (mul_22_8_n_87));
  INVXL mul_22_8_fopt455(.A (mul_22_8_n_91), .Y (mul_22_8_n_89));
  INVXL mul_22_8_fopt456(.A (mul_22_8_n_91), .Y (mul_22_8_n_90));
  INVXL mul_22_8_fopt457(.A (mul_22_8_n_25), .Y (mul_22_8_n_91));
  BUFX2 mul_22_8_fopt458(.A (mul_22_8_n_5), .Y (mul_22_8_n_93));
  INVXL mul_22_8_fopt459(.A (mul_22_8_n_96), .Y (mul_22_8_n_95));
  INVXL mul_22_8_fopt460(.A (mul_22_8_n_97), .Y (mul_22_8_n_96));
  CLKINVX1 mul_22_8_fopt461(.A (mul_22_8_n_98), .Y (mul_22_8_n_97));
  CLKINVX2 mul_22_8_fopt462(.A (mul_22_8_n_33), .Y (mul_22_8_n_98));
  INVXL mul_22_8_fopt463(.A (mul_22_8_n_103), .Y (mul_22_8_n_101));
  INVXL mul_22_8_fopt464(.A (mul_22_8_n_103), .Y (mul_22_8_n_102));
  INVXL mul_22_8_fopt465(.A (mul_22_8_n_62), .Y (mul_22_8_n_103));
  BUFX2 mul_22_8_fopt466(.A (mul_22_8_n_44), .Y (mul_22_8_n_106));
endmodule

