`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  6 2021 05:28:03 CST (May  5 2021 21:28:03 UTC)

module Gaussian_Blur_Div_11Ux2U_11U_1(in2, in1, out1);
  input [10:0] in2;
  input [1:0] in1;
  output [10:0] out1;
  wire [10:0] in2;
  wire [1:0] in1;
  wire [10:0] out1;
  wire in2_31_2_, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_27, n_29, n_30, n_31, n_32, n_33;
  wire n_37, n_38, n_39, n_40, n_41, n_42, n_43, n_44;
  wire n_45, n_46, n_47, n_48, n_49, n_50, n_51, n_52;
  wire n_53, n_54, n_55, n_56, n_57, n_58, n_59, n_60;
  wire n_61, n_62, n_63, n_64, n_65, n_66, n_67, n_68;
  wire n_69, n_70, n_71, n_72, n_73, n_74, n_75, n_76;
  wire n_77, n_79, n_80, n_81, n_82, n_83, n_84, n_90;
  wire n_96, n_130, sub_65_2_n_1, sub_65_2_n_2, sub_65_2_n_3,
       sub_86_2_n_0, sub_86_2_n_1, sub_86_2_n_2;
  wire sub_107_2_n_0, sub_107_2_n_1, sub_107_2_n_2, sub_107_2_n_5,
       sub_107_2_n_12, sub_128_2_n_0, sub_128_2_n_1, sub_128_2_n_2;
  wire sub_128_2_n_5, sub_128_2_n_12, sub_149_2_n_0, sub_149_2_n_1,
       sub_149_2_n_2, sub_149_2_n_5, sub_149_2_n_12, sub_170_2_n_0;
  wire sub_170_2_n_1, sub_170_2_n_2, sub_170_2_n_5, sub_170_2_n_12,
       sub_191_2_n_0, sub_191_2_n_1, sub_191_2_n_2, sub_191_2_n_3;
  wire sub_191_2_n_6, sub_212_2_n_0, sub_212_2_n_2, sub_212_2_n_3,
       sub_212_2_n_6, sub_212_2_n_14, sub_233_2_n_0, sub_233_2_n_1;
  wire sub_233_2_n_3, sub_233_2_n_4, sub_233_2_n_7, sub_254_2_n_0,
       sub_254_2_n_1, sub_254_2_n_2, sub_254_2_n_3, sub_254_2_n_4;
  wire sub_254_2_n_5, sub_254_2_n_7, sub_254_2_n_8, sub_254_2_n_10,
       sub_273_2_n_1, sub_273_2_n_2, sub_273_2_n_3, sub_273_2_n_4;
  wire sub_273_2_n_5;
  INVX1 g132(.A (in2_31_2_), .Y (out1[0]));
  NAND2X2 g114(.A (n_33), .B (n_32), .Y (n_82));
  NAND2X1 g115(.A (in2[10]), .B (n_84), .Y (n_33));
  NAND2X2 g116(.A (n_83), .B (n_31), .Y (n_32));
  CLKINVX2 g117(.A (n_84), .Y (n_31));
  NAND2X2 g125(.A (n_29), .B (n_30), .Y (n_77));
  OR2XL g127(.A (n_27), .B (n_81), .Y (n_30));
  NAND2X1 g128(.A (in2[9]), .B (n_81), .Y (n_29));
  INVX1 g130(.A (n_79), .Y (n_27));
  NAND2X2 g126(.A (n_25), .B (n_24), .Y (n_72));
  NAND2X1 g133(.A (in2[8]), .B (n_76), .Y (n_25));
  MX2XL g134(.A (n_75), .B (n_77), .S0 (n_76), .Y (n_73));
  NAND2BX1 g135(.AN (n_76), .B (n_74), .Y (n_24));
  NAND2X2 g136(.A (n_22), .B (n_23), .Y (n_67));
  OR2X1 g137(.A (n_21), .B (n_71), .Y (n_23));
  NAND2X1 g138(.A (in2[7]), .B (n_71), .Y (n_22));
  INVX1 g131(.A (n_69), .Y (n_21));
  MX2XL g139(.A (n_70), .B (n_72), .S0 (n_71), .Y (n_68));
  NAND2X2 g140(.A (n_19), .B (n_20), .Y (n_62));
  OR2XL g141(.A (n_18), .B (n_66), .Y (n_20));
  NAND2X1 g142(.A (in2[6]), .B (n_66), .Y (n_19));
  INVX1 g143(.A (n_64), .Y (n_18));
  MX2XL g144(.A (n_65), .B (n_67), .S0 (n_66), .Y (n_63));
  NAND2X2 g145(.A (n_16), .B (n_17), .Y (n_57));
  OR2X1 g146(.A (n_15), .B (n_61), .Y (n_17));
  NAND2X1 g147(.A (in2[5]), .B (n_61), .Y (n_16));
  INVX1 g148(.A (n_59), .Y (n_15));
  MX2XL g149(.A (n_60), .B (n_62), .S0 (n_61), .Y (n_58));
  OAI2BB1X1 g150(.A0N (n_56), .A1N (n_57), .B0 (n_11), .Y (n_53));
  NAND2X2 g151(.A (n_13), .B (n_14), .Y (n_52));
  OR2X1 g152(.A (n_12), .B (n_56), .Y (n_14));
  NAND2X1 g153(.A (in2[4]), .B (n_56), .Y (n_13));
  INVX1 g154(.A (n_54), .Y (n_12));
  NAND2BX1 g155(.AN (n_56), .B (n_55), .Y (n_11));
  OAI2BB1X1 g156(.A0N (n_51), .A1N (n_52), .B0 (n_8), .Y (n_48));
  OAI2BB1X1 g157(.A0N (in2[3]), .A1N (n_51), .B0 (n_10), .Y (n_47));
  OR2XL g158(.A (n_9), .B (n_51), .Y (n_10));
  INVXL g159(.A (n_49), .Y (n_9));
  NAND2BX1 g160(.AN (n_51), .B (n_50), .Y (n_8));
  OAI2BB1X1 g161(.A0N (n_130), .A1N (n_47), .B0 (n_5), .Y (n_43));
  OAI2BB1X1 g162(.A0N (in2[2]), .A1N (n_46), .B0 (n_7), .Y (n_42));
  OR2XL g163(.A (n_6), .B (n_46), .Y (n_7));
  INVXL g164(.A (n_44), .Y (n_6));
  NAND2BX1 g165(.AN (n_130), .B (n_45), .Y (n_5));
  MXI2XL g166(.A (n_3), .B (n_1), .S0 (n_96), .Y (n_38));
  OAI2BB1X1 g167(.A0N (in2[1]), .A1N (n_41), .B0 (n_4), .Y (n_37));
  OR2XL g168(.A (n_2), .B (n_41), .Y (n_4));
  INVX1 g169(.A (n_40), .Y (n_3));
  INVXL g170(.A (n_39), .Y (n_2));
  INVXL g171(.A (n_42), .Y (n_1));
  INVX1 g173(.A (n_84), .Y (out1[10]));
  INVX1 g118(.A (n_51), .Y (out1[3]));
  INVX1 g119(.A (n_56), .Y (out1[4]));
  INVX1 g120(.A (n_61), .Y (out1[5]));
  INVX1 g121(.A (n_66), .Y (out1[6]));
  INVX1 g122(.A (n_71), .Y (out1[7]));
  INVX1 g123(.A (n_76), .Y (out1[8]));
  INVX1 g175(.A (n_81), .Y (out1[9]));
  MX2XL g178(.A (n_80), .B (n_82), .S0 (n_81), .Y (n_90));
  CLKINVX1 fopt179(.A (n_96), .Y (out1[1]));
  BUFX3 fopt180(.A (n_41), .Y (n_96));
  CLKINVX1 fopt(.A (n_130), .Y (out1[2]));
  BUFX3 fopt182(.A (n_46), .Y (n_130));
  CLKXOR2X1 sub_149_2_g45(.A (n_68), .B (sub_149_2_n_5), .Y (n_66));
  ACHCONX2 sub_149_2_g46(.A (sub_149_2_n_2), .B (sub_149_2_n_1), .CI
       (n_67), .CON (sub_149_2_n_5));
  XNOR3XL sub_149_2_g47(.A (sub_149_2_n_2), .B (in1[1]), .C
       (sub_149_2_n_12), .Y (n_65));
  OAI2BB1X1 sub_149_2_g48(.A0N (in2[6]), .A1N (sub_149_2_n_0), .B0
       (sub_149_2_n_2), .Y (n_64));
  NAND2BX1 sub_149_2_g49(.AN (in2[6]), .B (in1[0]), .Y (sub_149_2_n_2));
  INVX1 sub_149_2_g50(.A (in1[1]), .Y (sub_149_2_n_1));
  INVXL sub_149_2_g51(.A (in1[0]), .Y (sub_149_2_n_0));
  BUFX3 sub_149_2_fopt(.A (n_67), .Y (sub_149_2_n_12));
  ACHCONX2 sub_86_2_g40(.A (sub_86_2_n_1), .B (sub_86_2_n_2), .CI
       (n_82), .CON (n_81));
  XOR3XL sub_86_2_g41(.A (sub_86_2_n_1), .B (sub_86_2_n_2), .C (n_82),
       .Y (n_80));
  NAND2X1 sub_86_2_g42(.A (sub_86_2_n_1), .B (sub_86_2_n_0), .Y (n_79));
  INVX2 sub_86_2_g46(.A (in1[1]), .Y (sub_86_2_n_2));
  NAND2BX4 sub_86_2_g2(.AN (in2[9]), .B (in1[0]), .Y (sub_86_2_n_1));
  NAND2BX1 sub_86_2_g48(.AN (in1[0]), .B (in2[9]), .Y (sub_86_2_n_0));
  MXI2X1 sub_254_2_g45(.A (sub_254_2_n_2), .B (n_43), .S0
       (sub_254_2_n_10), .Y (n_41));
  NOR2X1 sub_254_2_g46(.A (sub_254_2_n_5), .B (sub_254_2_n_8), .Y
       (sub_254_2_n_10));
  XNOR3XL sub_254_2_g47(.A (sub_254_2_n_4), .B (in1[1]), .C
       (sub_254_2_n_0), .Y (n_40));
  AOI2BB1XL sub_254_2_g48(.A0N (sub_254_2_n_3), .A1N (n_42), .B0
       (sub_254_2_n_7), .Y (sub_254_2_n_8));
  INVXL sub_254_2_g49(.A (sub_254_2_n_4), .Y (sub_254_2_n_7));
  OAI2BB1X1 sub_254_2_g50(.A0N (in2[1]), .A1N (sub_254_2_n_1), .B0
       (sub_254_2_n_4), .Y (n_39));
  AND2X1 sub_254_2_g51(.A (n_42), .B (sub_254_2_n_3), .Y
       (sub_254_2_n_5));
  NAND2BX1 sub_254_2_g52(.AN (in2[1]), .B (in1[0]), .Y (sub_254_2_n_4));
  INVX1 sub_254_2_g53(.A (in1[1]), .Y (sub_254_2_n_3));
  INVX1 sub_254_2_g54(.A (n_43), .Y (sub_254_2_n_2));
  INVX1 sub_254_2_g55(.A (in1[0]), .Y (sub_254_2_n_1));
  BUFX2 sub_254_2_fopt(.A (n_42), .Y (sub_254_2_n_0));
  CLKXOR2X1 sub_191_2_g45(.A (n_58), .B (sub_191_2_n_6), .Y (n_56));
  ACHCONX2 sub_191_2_g46(.A (sub_191_2_n_3), .B (sub_191_2_n_2), .CI
       (n_57), .CON (sub_191_2_n_6));
  XNOR3XL sub_191_2_g47(.A (sub_191_2_n_3), .B (in1[1]), .C
       (sub_191_2_n_0), .Y (n_55));
  OAI2BB1X1 sub_191_2_g48(.A0N (in2[4]), .A1N (sub_191_2_n_1), .B0
       (sub_191_2_n_3), .Y (n_54));
  NAND2BX1 sub_191_2_g49(.AN (in2[4]), .B (in1[0]), .Y (sub_191_2_n_3));
  INVX1 sub_191_2_g50(.A (in1[1]), .Y (sub_191_2_n_2));
  INVXL sub_191_2_g51(.A (in1[0]), .Y (sub_191_2_n_1));
  BUFX2 sub_191_2_fopt(.A (n_57), .Y (sub_191_2_n_0));
  CLKXOR2X1 sub_128_2_g45(.A (n_73), .B (sub_128_2_n_5), .Y (n_71));
  ACHCONX2 sub_128_2_g46(.A (sub_128_2_n_2), .B (sub_128_2_n_1), .CI
       (n_72), .CON (sub_128_2_n_5));
  XNOR3XL sub_128_2_g47(.A (sub_128_2_n_2), .B (in1[1]), .C
       (sub_128_2_n_12), .Y (n_70));
  OAI2BB1X1 sub_128_2_g48(.A0N (in2[7]), .A1N (sub_128_2_n_0), .B0
       (sub_128_2_n_2), .Y (n_69));
  NAND2BX1 sub_128_2_g49(.AN (in2[7]), .B (in1[0]), .Y (sub_128_2_n_2));
  INVX1 sub_128_2_g50(.A (in1[1]), .Y (sub_128_2_n_1));
  INVX1 sub_128_2_g51(.A (in1[0]), .Y (sub_128_2_n_0));
  BUFX3 sub_128_2_fopt(.A (n_72), .Y (sub_128_2_n_12));
  NAND2X1 sub_65_2_g31(.A (sub_65_2_n_1), .B (sub_65_2_n_2), .Y (n_83));
  CLKINVX4 sub_65_2_g35(.A (in2[10]), .Y (sub_65_2_n_3));
  NAND2X4 sub_65_2_g38(.A (in1[0]), .B (sub_65_2_n_3), .Y
       (sub_65_2_n_2));
  NAND2BX1 sub_65_2_g2(.AN (in1[0]), .B (in2[10]), .Y (sub_65_2_n_1));
  NAND2BX4 sub_65_2_g39(.AN (in1[1]), .B (sub_65_2_n_2), .Y (n_84));
  XOR2XL sub_273_2_g34(.A (n_38), .B (sub_273_2_n_5), .Y (in2_31_2_));
  NOR2X1 sub_273_2_g35(.A (sub_273_2_n_2), .B (sub_273_2_n_4), .Y
       (sub_273_2_n_5));
  AOI2BB1XL sub_273_2_g36(.A0N (sub_273_2_n_1), .A1N (n_37), .B0
       (sub_273_2_n_3), .Y (sub_273_2_n_4));
  NOR2BX1 sub_273_2_g37(.AN (in1[0]), .B (in2[0]), .Y (sub_273_2_n_3));
  AND2X1 sub_273_2_g38(.A (n_37), .B (sub_273_2_n_1), .Y
       (sub_273_2_n_2));
  INVX1 sub_273_2_g39(.A (in1[1]), .Y (sub_273_2_n_1));
  ACHCONX2 sub_233_2_g46(.A (sub_233_2_n_4), .B (sub_233_2_n_3), .CI
       (n_47), .CON (sub_233_2_n_7));
  XNOR3XL sub_233_2_g47(.A (sub_233_2_n_4), .B (in1[1]), .C
       (sub_233_2_n_0), .Y (n_45));
  OAI2BB1X1 sub_233_2_g48(.A0N (in2[2]), .A1N (sub_233_2_n_1), .B0
       (sub_233_2_n_4), .Y (n_44));
  NAND2BX1 sub_233_2_g49(.AN (in2[2]), .B (in1[0]), .Y (sub_233_2_n_4));
  INVX1 sub_233_2_g50(.A (in1[1]), .Y (sub_233_2_n_3));
  INVX1 sub_233_2_g52(.A (in1[0]), .Y (sub_233_2_n_1));
  BUFX2 sub_233_2_fopt(.A (n_47), .Y (sub_233_2_n_0));
  CLKXOR2X1 sub_233_2_g2(.A (n_48), .B (sub_233_2_n_7), .Y (n_46));
  CLKXOR2X1 sub_170_2_g45(.A (n_63), .B (sub_170_2_n_5), .Y (n_61));
  ACHCONX2 sub_170_2_g46(.A (sub_170_2_n_2), .B (sub_170_2_n_1), .CI
       (n_62), .CON (sub_170_2_n_5));
  XNOR3XL sub_170_2_g47(.A (sub_170_2_n_2), .B (in1[1]), .C
       (sub_170_2_n_12), .Y (n_60));
  OAI2BB1X1 sub_170_2_g48(.A0N (in2[5]), .A1N (sub_170_2_n_0), .B0
       (sub_170_2_n_2), .Y (n_59));
  NAND2BX1 sub_170_2_g49(.AN (in2[5]), .B (in1[0]), .Y (sub_170_2_n_2));
  INVX1 sub_170_2_g50(.A (in1[1]), .Y (sub_170_2_n_1));
  INVX1 sub_170_2_g51(.A (in1[0]), .Y (sub_170_2_n_0));
  BUFX3 sub_170_2_fopt(.A (n_62), .Y (sub_170_2_n_12));
  CLKXOR2X1 sub_107_2_g45(.A (n_90), .B (sub_107_2_n_5), .Y (n_76));
  ACHCONX2 sub_107_2_g46(.A (sub_107_2_n_2), .B (sub_107_2_n_0), .CI
       (n_77), .CON (sub_107_2_n_5));
  XNOR3XL sub_107_2_g47(.A (sub_107_2_n_2), .B (in1[1]), .C
       (sub_107_2_n_12), .Y (n_75));
  NAND2X1 sub_107_2_g48(.A (sub_107_2_n_2), .B (sub_107_2_n_1), .Y
       (n_74));
  NAND2BX1 sub_107_2_g49(.AN (in2[8]), .B (in1[0]), .Y (sub_107_2_n_2));
  NAND2BX1 sub_107_2_g50(.AN (in1[0]), .B (in2[8]), .Y (sub_107_2_n_1));
  INVX1 sub_107_2_g51(.A (in1[1]), .Y (sub_107_2_n_0));
  BUFX3 sub_107_2_fopt(.A (n_77), .Y (sub_107_2_n_12));
  ACHCONX2 sub_212_2_g46(.A (sub_212_2_n_3), .B (sub_212_2_n_2), .CI
       (n_52), .CON (sub_212_2_n_6));
  XNOR3XL sub_212_2_g47(.A (sub_212_2_n_3), .B (in1[1]), .C
       (sub_212_2_n_14), .Y (n_50));
  OAI2BB1X1 sub_212_2_g48(.A0N (in2[3]), .A1N (sub_212_2_n_0), .B0
       (sub_212_2_n_3), .Y (n_49));
  NAND2BX1 sub_212_2_g49(.AN (in2[3]), .B (in1[0]), .Y (sub_212_2_n_3));
  INVX1 sub_212_2_g50(.A (in1[1]), .Y (sub_212_2_n_2));
  INVX1 sub_212_2_g52(.A (in1[0]), .Y (sub_212_2_n_0));
  CLKXOR2X1 sub_212_2_g2(.A (n_53), .B (sub_212_2_n_6), .Y (n_51));
  BUFX3 sub_212_2_fopt(.A (n_52), .Y (sub_212_2_n_14));
endmodule

