`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  6 2021 05:27:24 CST (May  5 2021 21:27:24 UTC)

module Gaussian_Blur_Abs_32S_32U_4(in1, out1);
  input [31:0] in1;
  output [31:0] out1;
  wire [31:0] in1;
  wire [31:0] out1;
  wire minus_20_14_n_0, minus_20_14_n_1, minus_20_14_n_2,
       minus_20_14_n_3, minus_20_14_n_4, minus_20_14_n_5,
       minus_20_14_n_6, minus_20_14_n_7;
  wire minus_20_14_n_8, minus_20_14_n_9, minus_20_14_n_10,
       minus_20_14_n_11, minus_20_14_n_12, minus_20_14_n_13,
       minus_20_14_n_14, minus_20_14_n_15;
  wire minus_20_14_n_16, minus_20_14_n_17, minus_20_14_n_18,
       minus_20_14_n_19, minus_20_14_n_20, minus_20_14_n_21,
       minus_20_14_n_22, minus_20_14_n_23;
  wire minus_20_14_n_24, minus_20_14_n_25, minus_20_14_n_26,
       minus_20_14_n_27, minus_20_14_n_28, minus_20_14_n_29,
       minus_20_14_n_31, minus_20_14_n_33;
  wire minus_20_14_n_35, minus_20_14_n_37, minus_20_14_n_39,
       minus_20_14_n_42, minus_20_14_n_43, minus_20_14_n_44,
       minus_20_14_n_46, minus_20_14_n_49;
  wire minus_20_14_n_51, minus_20_14_n_53, minus_20_14_n_55,
       minus_20_14_n_58, minus_20_14_n_59, minus_20_14_n_60,
       minus_20_14_n_62, minus_20_14_n_65;
  wire minus_20_14_n_67, minus_20_14_n_69, minus_20_14_n_71,
       minus_20_14_n_73, minus_20_14_n_75, minus_20_14_n_77,
       minus_20_14_n_79, minus_20_14_n_81;
  wire minus_20_14_n_83, minus_20_14_n_85, minus_20_14_n_87, n_0, n_1,
       n_2, n_3, n_4;
  wire n_5, n_6, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_13, n_14, n_15, n_16, n_17, n_18, n_19, n_20;
  wire n_21, n_22, n_23, n_24, n_25, n_26, n_27, n_28;
  wire n_29, n_30;
  assign out1[0] = in1[0];
  MX2XL g310(.A (in1[17]), .B (n_16), .S0 (in1[31]), .Y (out1[17]));
  MX2XL g311(.A (in1[29]), .B (n_28), .S0 (in1[31]), .Y (out1[29]));
  MX2XL g312(.A (in1[27]), .B (n_26), .S0 (in1[31]), .Y (out1[27]));
  MX2XL g313(.A (in1[24]), .B (n_23), .S0 (in1[31]), .Y (out1[24]));
  MX2XL g314(.A (in1[18]), .B (n_17), .S0 (in1[31]), .Y (out1[18]));
  MX2XL g315(.A (in1[5]), .B (n_4), .S0 (in1[31]), .Y (out1[5]));
  MX2XL g316(.A (in1[4]), .B (n_3), .S0 (in1[31]), .Y (out1[4]));
  MX2XL g317(.A (in1[30]), .B (n_29), .S0 (in1[31]), .Y (out1[30]));
  MX2XL g318(.A (in1[3]), .B (n_2), .S0 (in1[31]), .Y (out1[3]));
  MX2XL g319(.A (in1[23]), .B (n_22), .S0 (in1[31]), .Y (out1[23]));
  MX2XL g320(.A (in1[16]), .B (n_15), .S0 (in1[31]), .Y (out1[16]));
  MX2XL g321(.A (in1[2]), .B (n_1), .S0 (in1[31]), .Y (out1[2]));
  MX2XL g322(.A (in1[1]), .B (n_0), .S0 (in1[31]), .Y (out1[1]));
  MX2XL g323(.A (in1[15]), .B (n_14), .S0 (in1[31]), .Y (out1[15]));
  MX2XL g324(.A (in1[22]), .B (n_21), .S0 (in1[31]), .Y (out1[22]));
  MX2XL g325(.A (in1[20]), .B (n_19), .S0 (in1[31]), .Y (out1[20]));
  MX2XL g326(.A (in1[13]), .B (n_12), .S0 (in1[31]), .Y (out1[13]));
  MX2XL g327(.A (in1[12]), .B (n_11), .S0 (in1[31]), .Y (out1[12]));
  MX2XL g328(.A (in1[28]), .B (n_27), .S0 (in1[31]), .Y (out1[28]));
  MX2XL g329(.A (in1[26]), .B (n_25), .S0 (in1[31]), .Y (out1[26]));
  MX2XL g330(.A (in1[21]), .B (n_20), .S0 (in1[31]), .Y (out1[21]));
  MX2XL g331(.A (in1[11]), .B (n_10), .S0 (in1[31]), .Y (out1[11]));
  MX2XL g332(.A (in1[14]), .B (n_13), .S0 (in1[31]), .Y (out1[14]));
  MX2XL g333(.A (in1[10]), .B (n_9), .S0 (in1[31]), .Y (out1[10]));
  MX2XL g334(.A (in1[9]), .B (n_8), .S0 (in1[31]), .Y (out1[9]));
  MX2XL g335(.A (in1[25]), .B (n_24), .S0 (in1[31]), .Y (out1[25]));
  MX2XL g336(.A (in1[19]), .B (n_18), .S0 (in1[31]), .Y (out1[19]));
  MX2XL g337(.A (in1[8]), .B (n_7), .S0 (in1[31]), .Y (out1[8]));
  MX2XL g338(.A (in1[7]), .B (n_6), .S0 (in1[31]), .Y (out1[7]));
  MX2XL g339(.A (in1[6]), .B (n_5), .S0 (in1[31]), .Y (out1[6]));
  AND2XL g340(.A (in1[31]), .B (n_30), .Y (out1[31]));
  XNOR2X1 minus_20_14_g780(.A (in1[31]), .B (minus_20_14_n_87), .Y
       (n_30));
  ADDHX1 minus_20_14_g781(.A (minus_20_14_n_5), .B (minus_20_14_n_85),
       .CO (minus_20_14_n_87), .S (n_29));
  ADDHX1 minus_20_14_g782(.A (minus_20_14_n_0), .B (minus_20_14_n_83),
       .CO (minus_20_14_n_85), .S (n_28));
  ADDHX1 minus_20_14_g783(.A (minus_20_14_n_26), .B (minus_20_14_n_81),
       .CO (minus_20_14_n_83), .S (n_27));
  ADDHX1 minus_20_14_g784(.A (minus_20_14_n_24), .B (minus_20_14_n_79),
       .CO (minus_20_14_n_81), .S (n_26));
  ADDHX1 minus_20_14_g785(.A (minus_20_14_n_11), .B (minus_20_14_n_77),
       .CO (minus_20_14_n_79), .S (n_25));
  ADDHX1 minus_20_14_g786(.A (minus_20_14_n_23), .B (minus_20_14_n_75),
       .CO (minus_20_14_n_77), .S (n_24));
  ADDHX1 minus_20_14_g787(.A (minus_20_14_n_27), .B (minus_20_14_n_73),
       .CO (minus_20_14_n_75), .S (n_23));
  ADDHX1 minus_20_14_g788(.A (minus_20_14_n_16), .B (minus_20_14_n_71),
       .CO (minus_20_14_n_73), .S (n_22));
  ADDHX1 minus_20_14_g789(.A (minus_20_14_n_7), .B (minus_20_14_n_69),
       .CO (minus_20_14_n_71), .S (n_21));
  ADDHX1 minus_20_14_g790(.A (minus_20_14_n_15), .B (minus_20_14_n_67),
       .CO (minus_20_14_n_69), .S (n_20));
  ADDHX1 minus_20_14_g791(.A (minus_20_14_n_20), .B (minus_20_14_n_65),
       .CO (minus_20_14_n_67), .S (n_19));
  ADDHX1 minus_20_14_g792(.A (minus_20_14_n_1), .B (minus_20_14_n_62),
       .CO (minus_20_14_n_65), .S (n_18));
  XNOR2X1 minus_20_14_g793(.A (in1[17]), .B (minus_20_14_n_60), .Y
       (n_16));
  ADDHX1 minus_20_14_g794(.A (minus_20_14_n_19), .B (minus_20_14_n_59),
       .CO (minus_20_14_n_62), .S (n_17));
  ADDHX1 minus_20_14_g795(.A (minus_20_14_n_13), .B (minus_20_14_n_58),
       .CO (minus_20_14_n_60), .S (n_15));
  NOR3BX1 minus_20_14_g796(.AN (minus_20_14_n_58), .B (in1[17]), .C
       (in1[16]), .Y (minus_20_14_n_59));
  ADDHX1 minus_20_14_g797(.A (minus_20_14_n_4), .B (minus_20_14_n_55),
       .CO (minus_20_14_n_58), .S (n_14));
  ADDHX1 minus_20_14_g798(.A (minus_20_14_n_17), .B (minus_20_14_n_53),
       .CO (minus_20_14_n_55), .S (n_13));
  ADDHX1 minus_20_14_g799(.A (minus_20_14_n_25), .B (minus_20_14_n_51),
       .CO (minus_20_14_n_53), .S (n_12));
  ADDHX1 minus_20_14_g800(.A (minus_20_14_n_3), .B (minus_20_14_n_49),
       .CO (minus_20_14_n_51), .S (n_11));
  ADDHX1 minus_20_14_g801(.A (minus_20_14_n_6), .B (minus_20_14_n_46),
       .CO (minus_20_14_n_49), .S (n_10));
  XNOR2X1 minus_20_14_g802(.A (in1[9]), .B (minus_20_14_n_44), .Y
       (n_8));
  ADDHX1 minus_20_14_g803(.A (minus_20_14_n_22), .B (minus_20_14_n_43),
       .CO (minus_20_14_n_46), .S (n_9));
  ADDHX1 minus_20_14_g804(.A (minus_20_14_n_14), .B (minus_20_14_n_42),
       .CO (minus_20_14_n_44), .S (n_7));
  NOR3BX1 minus_20_14_g805(.AN (minus_20_14_n_42), .B (in1[9]), .C
       (in1[8]), .Y (minus_20_14_n_43));
  ADDHX1 minus_20_14_g806(.A (minus_20_14_n_18), .B (minus_20_14_n_39),
       .CO (minus_20_14_n_42), .S (n_6));
  ADDHX1 minus_20_14_g807(.A (minus_20_14_n_9), .B (minus_20_14_n_37),
       .CO (minus_20_14_n_39), .S (n_5));
  ADDHX1 minus_20_14_g808(.A (minus_20_14_n_28), .B (minus_20_14_n_35),
       .CO (minus_20_14_n_37), .S (n_4));
  ADDHX1 minus_20_14_g809(.A (minus_20_14_n_8), .B (minus_20_14_n_33),
       .CO (minus_20_14_n_35), .S (n_3));
  ADDHX1 minus_20_14_g810(.A (minus_20_14_n_10), .B (minus_20_14_n_31),
       .CO (minus_20_14_n_33), .S (n_2));
  ADDHX1 minus_20_14_g811(.A (minus_20_14_n_12), .B (minus_20_14_n_29),
       .CO (minus_20_14_n_31), .S (n_1));
  ADDHX1 minus_20_14_g812(.A (minus_20_14_n_21), .B (minus_20_14_n_2),
       .CO (minus_20_14_n_29), .S (n_0));
  INVX1 minus_20_14_g813(.A (in1[5]), .Y (minus_20_14_n_28));
  INVX1 minus_20_14_g814(.A (in1[24]), .Y (minus_20_14_n_27));
  INVX1 minus_20_14_g815(.A (in1[28]), .Y (minus_20_14_n_26));
  INVX1 minus_20_14_g816(.A (in1[13]), .Y (minus_20_14_n_25));
  INVX1 minus_20_14_g817(.A (in1[27]), .Y (minus_20_14_n_24));
  INVX1 minus_20_14_g818(.A (in1[25]), .Y (minus_20_14_n_23));
  INVX1 minus_20_14_g819(.A (in1[10]), .Y (minus_20_14_n_22));
  INVX1 minus_20_14_g820(.A (in1[1]), .Y (minus_20_14_n_21));
  INVX1 minus_20_14_g821(.A (in1[20]), .Y (minus_20_14_n_20));
  INVX1 minus_20_14_g822(.A (in1[18]), .Y (minus_20_14_n_19));
  INVX1 minus_20_14_g823(.A (in1[7]), .Y (minus_20_14_n_18));
  INVX1 minus_20_14_g824(.A (in1[14]), .Y (minus_20_14_n_17));
  INVX1 minus_20_14_g825(.A (in1[23]), .Y (minus_20_14_n_16));
  INVX1 minus_20_14_g826(.A (in1[21]), .Y (minus_20_14_n_15));
  INVX1 minus_20_14_g827(.A (in1[8]), .Y (minus_20_14_n_14));
  INVX1 minus_20_14_g828(.A (in1[16]), .Y (minus_20_14_n_13));
  INVX1 minus_20_14_g829(.A (in1[2]), .Y (minus_20_14_n_12));
  INVX1 minus_20_14_g830(.A (in1[26]), .Y (minus_20_14_n_11));
  INVX1 minus_20_14_g831(.A (in1[3]), .Y (minus_20_14_n_10));
  INVX1 minus_20_14_g832(.A (in1[6]), .Y (minus_20_14_n_9));
  INVX1 minus_20_14_g833(.A (in1[4]), .Y (minus_20_14_n_8));
  INVX1 minus_20_14_g834(.A (in1[22]), .Y (minus_20_14_n_7));
  INVX1 minus_20_14_g835(.A (in1[11]), .Y (minus_20_14_n_6));
  INVX1 minus_20_14_g836(.A (in1[30]), .Y (minus_20_14_n_5));
  INVX1 minus_20_14_g837(.A (in1[15]), .Y (minus_20_14_n_4));
  INVX1 minus_20_14_g838(.A (in1[12]), .Y (minus_20_14_n_3));
  INVX1 minus_20_14_g839(.A (in1[0]), .Y (minus_20_14_n_2));
  INVX1 minus_20_14_g840(.A (in1[19]), .Y (minus_20_14_n_1));
  INVX1 minus_20_14_g841(.A (in1[29]), .Y (minus_20_14_n_0));
endmodule

