`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  6 2021 05:28:41 CST (May  5 2021 21:28:41 UTC)

module Gaussian_Blur_Add_11Sx10S_11S_1(in2, in1, out1);
  input [10:0] in2;
  input [9:0] in1;
  output [10:0] out1;
  wire [10:0] in2;
  wire [9:0] in1;
  wire [10:0] out1;
  wire add_23_2_n_1, add_23_2_n_2, add_23_2_n_11, add_23_2_n_12,
       add_23_2_n_13, add_23_2_n_14, add_23_2_n_15, add_23_2_n_16;
  wire add_23_2_n_17, add_23_2_n_18, add_23_2_n_19, add_23_2_n_20,
       add_23_2_n_21, add_23_2_n_22, add_23_2_n_23, add_23_2_n_24;
  wire add_23_2_n_25, add_23_2_n_26, add_23_2_n_27, add_23_2_n_28,
       add_23_2_n_29, add_23_2_n_30, add_23_2_n_31, add_23_2_n_32;
  wire add_23_2_n_33, add_23_2_n_34, add_23_2_n_35, add_23_2_n_36,
       add_23_2_n_37, add_23_2_n_38, add_23_2_n_39, add_23_2_n_40;
  wire add_23_2_n_41, add_23_2_n_42, add_23_2_n_43, add_23_2_n_44,
       add_23_2_n_45, add_23_2_n_46, add_23_2_n_47, add_23_2_n_48;
  wire add_23_2_n_49, add_23_2_n_50, add_23_2_n_51, add_23_2_n_52,
       add_23_2_n_54, add_23_2_n_55, add_23_2_n_56, add_23_2_n_57;
  wire add_23_2_n_58, add_23_2_n_60, add_23_2_n_61, add_23_2_n_62,
       add_23_2_n_63, add_23_2_n_64, add_23_2_n_65, add_23_2_n_66;
  wire add_23_2_n_70, add_23_2_n_71, add_23_2_n_94, add_23_2_n_95,
       add_23_2_n_96, add_23_2_n_98, add_23_2_n_99, add_23_2_n_100;
  wire add_23_2_n_101, add_23_2_n_104, add_23_2_n_107, add_23_2_n_108,
       add_23_2_n_109, add_23_2_n_111, add_23_2_n_112, add_23_2_n_113;
  MXI2XL add_23_2_g229(.A (add_23_2_n_44), .B (add_23_2_n_43), .S0
       (add_23_2_n_70), .Y (out1[9]));
  OAI21X1 add_23_2_g230(.A0 (add_23_2_n_40), .A1 (add_23_2_n_96), .B0
       (add_23_2_n_51), .Y (add_23_2_n_71));
  OAI21X1 add_23_2_g231(.A0 (add_23_2_n_26), .A1 (add_23_2_n_95), .B0
       (add_23_2_n_21), .Y (add_23_2_n_70));
  MXI2XL add_23_2_g233(.A (add_23_2_n_48), .B (add_23_2_n_47), .S0
       (add_23_2_n_63), .Y (out1[7]));
  MXI2XL add_23_2_g234(.A (add_23_2_n_38), .B (add_23_2_n_37), .S0
       (add_23_2_n_65), .Y (out1[6]));
  OAI21X2 add_23_2_g237(.A0 (add_23_2_n_54), .A1 (add_23_2_n_61), .B0
       (add_23_2_n_57), .Y (add_23_2_n_66));
  OAI21X1 add_23_2_g238(.A0 (add_23_2_n_42), .A1 (add_23_2_n_104), .B0
       (add_23_2_n_111), .Y (add_23_2_n_65));
  OAI21X1 add_23_2_g239(.A0 (add_23_2_n_15), .A1 (add_23_2_n_104), .B0
       (add_23_2_n_107), .Y (add_23_2_n_64));
  OAI21X1 add_23_2_g242(.A0 (add_23_2_n_55), .A1 (add_23_2_n_104), .B0
       (add_23_2_n_58), .Y (add_23_2_n_63));
  OAI21X1 add_23_2_g243(.A0 (add_23_2_n_19), .A1 (add_23_2_n_99), .B0
       (add_23_2_n_27), .Y (add_23_2_n_62));
  NOR2X4 add_23_2_g246(.A (add_23_2_n_49), .B (add_23_2_n_60), .Y
       (add_23_2_n_61));
  NOR2X2 add_23_2_g247(.A (add_23_2_n_1), .B (add_23_2_n_100), .Y
       (add_23_2_n_60));
  AOI2BB1X1 add_23_2_g249(.A0N (add_23_2_n_24), .A1N (add_23_2_n_112),
       .B0 (add_23_2_n_17), .Y (add_23_2_n_58));
  AOI21X2 add_23_2_g250(.A0 (add_23_2_n_45), .A1 (add_23_2_n_52), .B0
       (add_23_2_n_50), .Y (add_23_2_n_57));
  OAI21X4 add_23_2_g251(.A0 (add_23_2_n_12), .A1 (add_23_2_n_29), .B0
       (add_23_2_n_31), .Y (add_23_2_n_56));
  OR2XL add_23_2_g254(.A (add_23_2_n_24), .B (add_23_2_n_42), .Y
       (add_23_2_n_55));
  NAND2X1 add_23_2_g255(.A (add_23_2_n_45), .B (add_23_2_n_41), .Y
       (add_23_2_n_54));
  OAI21X2 add_23_2_g257(.A0 (add_23_2_n_13), .A1 (add_23_2_n_14), .B0
       (add_23_2_n_30), .Y (add_23_2_n_52));
  OA21X1 add_23_2_g258(.A0 (add_23_2_n_21), .A1 (add_23_2_n_25), .B0
       (add_23_2_n_32), .Y (add_23_2_n_51));
  OAI21X1 add_23_2_g259(.A0 (add_23_2_n_16), .A1 (add_23_2_n_20), .B0
       (add_23_2_n_22), .Y (add_23_2_n_50));
  OAI21X2 add_23_2_g260(.A0 (add_23_2_n_27), .A1 (add_23_2_n_28), .B0
       (add_23_2_n_23), .Y (add_23_2_n_49));
  INVX1 add_23_2_g261(.A (add_23_2_n_47), .Y (add_23_2_n_48));
  INVX1 add_23_2_g263(.A (add_23_2_n_43), .Y (add_23_2_n_44));
  INVX1 add_23_2_g264(.A (add_23_2_n_41), .Y (add_23_2_n_42));
  OR2XL add_23_2_g265(.A (add_23_2_n_25), .B (add_23_2_n_26), .Y
       (add_23_2_n_40));
  NOR2BX1 add_23_2_g266(.AN (add_23_2_n_22), .B (add_23_2_n_20), .Y
       (add_23_2_n_47));
  NAND2BX1 add_23_2_g267(.AN (add_23_2_n_26), .B (add_23_2_n_21), .Y
       (add_23_2_n_46));
  NOR2X1 add_23_2_g269(.A (add_23_2_n_20), .B (add_23_2_n_24), .Y
       (add_23_2_n_45));
  NOR2BX1 add_23_2_g270(.AN (add_23_2_n_32), .B (add_23_2_n_25), .Y
       (add_23_2_n_43));
  NOR2X1 add_23_2_g271(.A (add_23_2_n_14), .B (add_23_2_n_15), .Y
       (add_23_2_n_41));
  INVX1 add_23_2_g273(.A (add_23_2_n_37), .Y (add_23_2_n_38));
  NAND2BX1 add_23_2_g280(.AN (add_23_2_n_15), .B (add_23_2_n_108), .Y
       (add_23_2_n_39));
  NOR2X1 add_23_2_g281(.A (add_23_2_n_17), .B (add_23_2_n_24), .Y
       (add_23_2_n_37));
  NOR2BX1 add_23_2_g282(.AN (add_23_2_n_23), .B (add_23_2_n_28), .Y
       (add_23_2_n_36));
  NAND2X1 add_23_2_g283(.A (add_23_2_n_27), .B (add_23_2_n_18), .Y
       (add_23_2_n_35));
  XNOR2X1 add_23_2_g284(.A (in2[10]), .B (in1[9]), .Y (add_23_2_n_34));
  NOR2BX1 add_23_2_g285(.AN (add_23_2_n_30), .B (add_23_2_n_14), .Y
       (add_23_2_n_33));
  NAND2X1 add_23_2_g288(.A (in2[9]), .B (in1[9]), .Y (add_23_2_n_32));
  NAND2X2 add_23_2_g289(.A (in2[1]), .B (in1[1]), .Y (add_23_2_n_31));
  NAND2X1 add_23_2_g290(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_30));
  NOR2X8 add_23_2_g291(.A (in2[1]), .B (in1[1]), .Y (add_23_2_n_29));
  NOR2X4 add_23_2_g292(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_28));
  NAND2X2 add_23_2_g293(.A (in2[2]), .B (in1[2]), .Y (add_23_2_n_27));
  NOR2X1 add_23_2_g294(.A (in2[8]), .B (in1[8]), .Y (add_23_2_n_26));
  NOR2X1 add_23_2_g295(.A (in2[9]), .B (in1[9]), .Y (add_23_2_n_25));
  NOR2X1 add_23_2_g296(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_24));
  INVX1 add_23_2_g297(.A (add_23_2_n_18), .Y (add_23_2_n_19));
  INVX1 add_23_2_g298(.A (add_23_2_n_16), .Y (add_23_2_n_17));
  NAND2X1 add_23_2_g299(.A (in2[3]), .B (in1[3]), .Y (add_23_2_n_23));
  NAND2X1 add_23_2_g300(.A (in2[7]), .B (in1[7]), .Y (add_23_2_n_22));
  NAND2X1 add_23_2_g301(.A (in2[8]), .B (in1[8]), .Y (add_23_2_n_21));
  NOR2X2 add_23_2_g302(.A (in2[7]), .B (in1[7]), .Y (add_23_2_n_20));
  NAND2X2 add_23_2_g303(.A (add_23_2_n_101), .B (add_23_2_n_11), .Y
       (add_23_2_n_18));
  NAND2X1 add_23_2_g304(.A (in2[6]), .B (in1[6]), .Y (add_23_2_n_16));
  NOR2X1 add_23_2_g305(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_15));
  NOR2X2 add_23_2_g306(.A (in2[5]), .B (in1[5]), .Y (add_23_2_n_14));
  NAND2X1 add_23_2_g307(.A (in2[4]), .B (in1[4]), .Y (add_23_2_n_13));
  NAND2X6 add_23_2_g308(.A (in2[0]), .B (in1[0]), .Y (add_23_2_n_12));
  CLKINVX2 add_23_2_g309(.A (in1[2]), .Y (add_23_2_n_11));
  CLKXOR2X1 add_23_2_g2(.A (add_23_2_n_39), .B (add_23_2_n_104), .Y
       (out1[4]));
  XNOR2X1 add_23_2_g312(.A (add_23_2_n_12), .B (add_23_2_n_2), .Y
       (out1[1]));
  XNOR2X1 add_23_2_g313(.A (add_23_2_n_46), .B (add_23_2_n_94), .Y
       (out1[8]));
  CLKXOR2X1 add_23_2_g314(.A (add_23_2_n_36), .B (add_23_2_n_62), .Y
       (out1[3]));
  XNOR2X1 add_23_2_g315(.A (add_23_2_n_35), .B (add_23_2_n_98), .Y
       (out1[2]));
  XNOR2XL add_23_2_g316(.A (add_23_2_n_34), .B (add_23_2_n_71), .Y
       (out1[10]));
  XOR2XL add_23_2_g317(.A (add_23_2_n_33), .B (add_23_2_n_64), .Y
       (out1[5]));
  NOR2BX1 add_23_2_g318(.AN (add_23_2_n_31), .B (add_23_2_n_29), .Y
       (add_23_2_n_2));
  NAND2BX1 add_23_2_g319(.AN (add_23_2_n_28), .B (add_23_2_n_18), .Y
       (add_23_2_n_1));
  CLKXOR2X1 add_23_2_g320(.A (in2[0]), .B (in1[0]), .Y (out1[0]));
  INVXL add_23_2_fopt(.A (add_23_2_n_95), .Y (add_23_2_n_94));
  CLKINVX1 add_23_2_fopt321(.A (add_23_2_n_66), .Y (add_23_2_n_95));
  CLKINVX1 add_23_2_fopt322(.A (add_23_2_n_66), .Y (add_23_2_n_96));
  INVXL add_23_2_fopt323(.A (add_23_2_n_99), .Y (add_23_2_n_98));
  BUFX3 add_23_2_fopt324(.A (add_23_2_n_100), .Y (add_23_2_n_99));
  CLKINVX3 add_23_2_fopt325(.A (add_23_2_n_56), .Y (add_23_2_n_100));
  CLKINVX3 add_23_2_fopt326(.A (in2[2]), .Y (add_23_2_n_101));
  BUFX3 add_23_2_fopt327(.A (add_23_2_n_61), .Y (add_23_2_n_104));
  INVXL add_23_2_fopt328(.A (add_23_2_n_109), .Y (add_23_2_n_107));
  INVXL add_23_2_fopt329(.A (add_23_2_n_109), .Y (add_23_2_n_108));
  INVXL add_23_2_fopt330(.A (add_23_2_n_13), .Y (add_23_2_n_109));
  INVXL add_23_2_fopt331(.A (add_23_2_n_113), .Y (add_23_2_n_111));
  INVXL add_23_2_fopt332(.A (add_23_2_n_113), .Y (add_23_2_n_112));
  BUFX2 add_23_2_fopt333(.A (add_23_2_n_52), .Y (add_23_2_n_113));
endmodule

