// Generated by stratus_hls 19.12-s100  (91710.131054)
// Thu May  6 05:34:07 2021
// from ../Gaussian_Blur.cpp

`timescale 1ps / 1ps

      
module Gaussian_Blur_ROM_9X9_filter_const(in1, out1, clk);

      input [3:0] in1;
      input clk;
      output [8:0] out1;
      reg [8:0] out1;
      reg[8:0] filter_const[8:0];

         initial begin
            $readmemh("bdw_work/modules/Gaussian_Blur/DPA/Gaussian_Blur_ROM_9X9_filter_const_1.memh", filter_const);
         end

         always @(posedge clk)
          begin :Gaussian_Blur_ROM_9X9_filter_const_filter_const_thread_1
            if (in1 < 4'd09) begin
               out1 <= filter_const[in1];
            end
         end


endmodule

