`timescale 1ps / 1ps

// Generated by Cadence Genus(TM) Synthesis Solution 17.11-s014_1
// Generated on: May  6 2021 05:52:59 CST (May  5 2021 21:52:59 UTC)

module Gaussian_Blur_Minus_11U_11S_4(in1, out1);
  input [10:0] in1;
  output [10:0] out1;
  wire [10:0] in1;
  wire [10:0] out1;
  wire minus_20_2_n_0, minus_20_2_n_1, minus_20_2_n_2, minus_20_2_n_3,
       minus_20_2_n_4, minus_20_2_n_5, minus_20_2_n_6, minus_20_2_n_7;
  wire minus_20_2_n_8, minus_20_2_n_9, minus_20_2_n_10,
       minus_20_2_n_12, minus_20_2_n_14, minus_20_2_n_16,
       minus_20_2_n_18, minus_20_2_n_20;
  wire minus_20_2_n_22, minus_20_2_n_24, minus_20_2_n_26;
  assign out1[0] = in1[0];
  XNOR2X1 minus_20_2_g237(.A (in1[10]), .B (minus_20_2_n_26), .Y
       (out1[10]));
  ADDHX1 minus_20_2_g238(.A (minus_20_2_n_3), .B (minus_20_2_n_24), .CO
       (minus_20_2_n_26), .S (out1[9]));
  ADDHX1 minus_20_2_g239(.A (minus_20_2_n_9), .B (minus_20_2_n_22), .CO
       (minus_20_2_n_24), .S (out1[8]));
  ADDHX1 minus_20_2_g240(.A (minus_20_2_n_7), .B (minus_20_2_n_20), .CO
       (minus_20_2_n_22), .S (out1[7]));
  ADDHX1 minus_20_2_g241(.A (minus_20_2_n_5), .B (minus_20_2_n_18), .CO
       (minus_20_2_n_20), .S (out1[6]));
  ADDHX1 minus_20_2_g242(.A (minus_20_2_n_1), .B (minus_20_2_n_16), .CO
       (minus_20_2_n_18), .S (out1[5]));
  ADDHX1 minus_20_2_g243(.A (minus_20_2_n_0), .B (minus_20_2_n_14), .CO
       (minus_20_2_n_16), .S (out1[4]));
  ADDHX1 minus_20_2_g244(.A (minus_20_2_n_2), .B (minus_20_2_n_12), .CO
       (minus_20_2_n_14), .S (out1[3]));
  ADDHX1 minus_20_2_g245(.A (minus_20_2_n_8), .B (minus_20_2_n_10), .CO
       (minus_20_2_n_12), .S (out1[2]));
  ADDHX1 minus_20_2_g246(.A (minus_20_2_n_4), .B (minus_20_2_n_6), .CO
       (minus_20_2_n_10), .S (out1[1]));
  INVX1 minus_20_2_g247(.A (in1[8]), .Y (minus_20_2_n_9));
  INVX1 minus_20_2_g248(.A (in1[2]), .Y (minus_20_2_n_8));
  INVX1 minus_20_2_g249(.A (in1[7]), .Y (minus_20_2_n_7));
  INVX1 minus_20_2_g250(.A (in1[0]), .Y (minus_20_2_n_6));
  INVX1 minus_20_2_g251(.A (in1[6]), .Y (minus_20_2_n_5));
  INVX1 minus_20_2_g252(.A (in1[1]), .Y (minus_20_2_n_4));
  INVX1 minus_20_2_g253(.A (in1[9]), .Y (minus_20_2_n_3));
  INVX1 minus_20_2_g254(.A (in1[3]), .Y (minus_20_2_n_2));
  INVX1 minus_20_2_g255(.A (in1[5]), .Y (minus_20_2_n_1));
  INVX1 minus_20_2_g256(.A (in1[4]), .Y (minus_20_2_n_0));
endmodule


